<?php defined('SYSPATH') or die('No direct access allowed.');

    return Model_Factory_Items::factory()
        ->add(Model_Items_Matches::cls(), 2)
        ->add(Model_Items_Heatjacket4::cls(), 1)
        ->add(Model_Items_Generic_Wire::cls()       , 1)
        ->add(Model_Items_Generic_Sum::cls()		    , 2)
        ->add(Model_Items_Generic_Metal::cls()		    , 4)
        ->add(Model_Items_Generic_Tube::cls()		    , 3)
        ->add(Model_Items_Generic_Wood::cls()		    , 2)
        ->add(Model_Items_Generic_Ducttape::cls()	, 4)
        ->add(Model_Items_Generic_Motor::cls()		    , 1)
        ->add(Model_Items_Battery::cls()			    , 2)
        ->add(Model_Items_Generic_Gunpowder::cls()	, 1)
        ->add(Model_Items_Generic_Bed::cls()		    , 1)
        ->add(Model_Items_Generic_Electro::cls()	    , 2)
        ->add(Model_Items_Generic_Electro2::cls()	    , 1)
        ->add(Model_Items_Generic_Pressure::cls()	, 2)
        ->add(Model_Items_Generic_Plasticbag::cls() , 2)
        ->add(Model_Items_Money::cls()			    , 1)
        ->add(Model_Items_Generic_Table::cls()	    , 2)
        ->add(Model_Items_Booklet::cls()            , 1)
        ->add(Model_Items_Shield::cls()	            , 1)
        ->add(Model_Items_Helmet::cls()             , 1)
        ->add(Model_Items_Bat::cls()                , 1)
        ->add(Model_Items_Shield3::cls()            , 1)
        ->add(Model_Items_Generic_Belt::cls()       , 1)
        ->add(Model_Items_Generic_Spraycan::cls(), 1)
        ->add(Model_Items_Bigbottle::cls(), 1)
        ;