<?php defined('SYSPATH') or die('No direct access allowed.');

return array(
    'groups' => array(
        'body' => array(
                'Model_Items_Body'              =>      5,
                'Model_Items_Body2'              =>     1,
                'Model_Items_Body3'              =>     2,
        ),
        'useless' => array(
                'Model_Items_Generic_Crwood'	=>		3,
                'Model_Items_Generic_Crmetal'	=>		2,
        ),
        'literature' => array(
                'Model_Items_Magazine'          =>      4,
                'Model_Items_Book'              =>      1,
                'Model_Items_Pamphlet'          =>      1,
        ),
        'fastfood' => array(
                'Model_Items_Softdrink'			=>		3,
                'Model_Items_Fastfood'			=>		5,
                'Model_Items_Nutrient'			=>		1,
                'Model_Items_Lunchbag'			=>		1,
                'Model_Items_Money'				=>		1,
        ),
        'kitchenutils' => array(
                'Model_Items_Generic_Tube'		=>		1,
                'Model_Items_Generic_Table'		=>		1,
                'Model_Items_Generic_Boiler'	=>		1,
                'Model_Items_Gardenchair2'		=>		4,
                'Model_Items_Gardenchair'		=>		2,
                'Model_Items_Generic_Cloth'		=>		2,
                'Model_Items_Smallbottle'		=>		1,
                'Model_Items_Generic_Plasticbag'=>		1,
                'Model_Items_Generic_Mixer'		=>		1,
                'Model_Items_Generic_Oven'		=>		1,
                'Model_Items_Knife'				=>		1,
                'Model_Items_Clock'             =>      1
        ),
        'kitchenfood' => array(
                'Model_Items_Basefood'			=>		3,
                'alcohol'						=>		1,
                'Model_Items_Coffee'			=>		1,
                'Model_Items_Lunchbag'			=>		1,
                'Model_Items_Generic_Water1'	=>		1,
                'Model_Items_Dalad'             =>      1,
                'Model_Items_Generic_Spice'     =>      1,
        ),
        'gardening' => array(
                'Model_Items_Gardenchair'		=>		3,
                'Model_Items_Generic_Water2'	=>		1,
                'Model_Items_Generic_Wood'		=>		2,
                'Model_Items_Generic_Tube'		=>		2,
                'Model_Items_Generic_Micropur'	=>		1,
                'Model_Items_Shield'	        =>		1,
                'Model_Items_Helmet'            =>      1,
                'Model_Items_Generic_Bike'      =>      1,
        ),
        'diy' => array(
                'Model_Items_Generic_Wire'      =>      1,
                'Model_Items_Generic_Jerrycan'	=>		1,
                'Model_Items_Generic_Sum'		=>		2,
                'Model_Items_Generic_Metal'		=>		4,
                'Model_Items_Generic_Tube'		=>		3,
                'Model_Items_Generic_Wood'		=>		3,
                'Model_Items_Generic_Ducttape'	=>		4,
                'Model_Items_Generic_Motor'		=>		1,
                'Model_Items_Battery'			=>		3,
                'Model_Items_Generic_Gunpowder'	=>		1,
                'Model_Items_Generic_Bed'		=>		1,
                'Model_Items_Generic_Electro'	=>		2,
                'Model_Items_Generic_Pressure'	=>		2,
                'Model_Items_Generic_Plasticbag'=>		2,
                'Model_Items_Money'				=>		2,
                'Model_Items_Generic_Table'		=>		2,
                'Model_Items_Chainsaw'          =>      1,
                'Model_Items_Booklet'           =>      2,
                'Model_Items_Shield'	        =>		2,
                'Model_Items_Helmet'            =>      2,
                'Model_Items_Clock'             =>      1,
                'Model_Items_Bat'               =>      1,
                'Model_Items_Shield3'           =>      1,
                'Model_Items_Phone'             =>      1,
                'Model_Items_Flashlight'        =>      1,
                'Model_Items_Generic_Bike'      =>      1,
                'Model_Items_Tentkit'           =>      1,
        ),
        'hideout' => array(
                'Model_Items_Generic_Bed'		=>		1,
                'body'          				=>		5,
                'Model_Items_Battery'			=>		3,
                'Model_Items_Generic_Lamp'		=>		1,
                'Model_Items_Ammo'				=>		1,
                'Model_Items_Handgun'			=>		1,
                'Model_Items_Oldrifle'          =>      1,
                'Model_Items_Generic_Gunpowder'	=>		2,
                'Model_Items_Generic_Cloth'		=>		3,
                'water'							=>		2,
                'Model_Items_Generic_Plasticbag'=>		1,
                'Model_Items_Generic_Teddy'		=>		2,
                'Model_Items_Bottle'			=>		1,
                'Model_Items_Knife'				=>		2,
                'Model_Items_Generic_Oven'		=>		1,
                'Model_Items_Money'				=>		1,
                'Model_Items_Generic_Table'		=>		1,
                'Model_Items_Chainsaw'          =>      1,
                'Model_Items_Bandage2'          =>      2,
                'Model_Items_Meds'              =>      1,
                'Model_Items_Dalad'             =>      1,
                'Model_Items_Dildo'             =>      1,
                'literature'                    =>      1,
                'Model_Items_Shield'	        =>		1,
                'Model_Items_Vest'              =>      1,
                'Model_Items_Clock'             =>      1,
                'Model_Items_Bat'               =>      2,
                'Model_Items_Jacket'            =>      1,
                'Model_Items_Phone'             =>      1,
                'Model_Items_Flashlight'        =>      2,
                'Model_Items_Tentkit'           =>      1,
        ),
        'water' => array(
                'Model_Items_Generic_Water0'	=>		1,
                'Model_Items_Generic_Water1'	=>		2,
                'Model_Items_Generic_Water2'	=>		2,
        ),
        'swater' => array(
            'Model_Items_Generic_Water2'	=>		2,
            'Model_Items_Generic_Water1'	=>		1,
            'Model_Items_Cwater'	        =>		3,
            'Model_Items_Cwater2'	        =>		4,
        ),
        'bedroom' => array(
                'Model_Items_Generic_Bed'		=>		2,
                'Model_Items_Battery'			=>		1,
                'Model_Items_Generic_Lamp'		=>		2,
                'Model_Items_Generic_Cloth'		=>		2,
                'Model_Items_Generic_Teddy'		=>		2,
                'Model_Items_Dildo'             =>      3,
                'literature'                    =>      2,
                'Model_Items_Helmet'            =>      1,
                'Model_Items_Clock'             =>      2,
                'Model_Items_Jacket'              =>    1,
        ),
        'meds' => array(
                'Model_Items_Paracetin'			=>		2,
                'Model_Items_Paracetoid'		=>		2,
                'Model_Items_Paralaxium'		=>		2,
                'Model_Items_Nutrient'			=>		1,
                'Model_Items_Pill'				=>		1,
                'Model_Items_Bandage'			=>		1,
                'Model_Items_Generic_Micropur'	=>		1,
                'Model_Items_Meds'              =>      2,
        ),
        'smeds' => array(
            'Model_Items_Paracetin'			=>		2,
            'Model_Items_Paracetoid'		=>		2,
            'Model_Items_Paralaxium'		=>		2,
            'Model_Items_Nutrient'			=>		1,
            'Model_Items_Pill'				=>		1,
            'Model_Items_Bandage'			=>		1,
            'Model_Items_Generic_Micropur'	=>		1,
            'Model_Items_Meds'              =>      2,
            'Model_Items_Uniheal'           =>      1,
            'Model_Items_Uniheal2'          =>      1,
        ),
        'druglab' => array(
                'Model_Items_Chem'				=>		2,
                'Model_Items_Powderpack'		=>		1,
                'Model_Items_Nutrient'			=>		1,
                'Model_Items_Pill'				=>		2,
                'Model_Items_Bandage'			=>		1,
                'alcohol'						=>		1,
                'Model_Items_Generic_Micropur'	=>		1,
                'Model_Items_Generic_Oven'		=>		1,
                'Model_Items_Money'				=>		2,
                'Model_Items_Generic_Table'		=>		1,
                'Model_Items_Meds'              =>      1,
                'Model_Items_Dildo'             =>      1,
                'Model_Items_Generic_Spice'     =>      1,
                'Model_Items_Shield'	        =>		1,
                'Model_Items_Helmet'            =>      2,
                'Model_Items_Jacket'            =>      1,
                'Model_Items_Shield3'           =>      1,
        ),
        'alcohol' => array(
                'Model_Items_Beer'				=>		2,
                'Model_Items_Whiskey'			=>		1,
        ),
        'ammo' => array(
                'Model_Items_Battery'			=>		3,
                'Model_Items_Ammo'				=>		1,
                'Model_Items_Generic_Tube'		=>		1,
                'Model_Items_Generic_Gunpowder'	=>		2,
        ),
        'weapons' => array(
                'Model_Items_Generic_Plasticbag'=>		4,
                'Model_Items_Oldrifle'          =>      1,
                'Model_Items_Handgun'			=>		1,
                'Model_Items_Watergun'			=>		2,
                'Model_Items_Knife'				=>		1,
                'Model_Items_Chainsaw'          =>      1,
                'Model_Items_Vest'              =>      1,
                'Model_Items_Bat'               =>      1,
                'Model_Items_Flashlight'        =>      1,
        ),
        'xmas' => array(
                'Model_Items_Generic_Spice'     =>      1,
                'Model_Items_Generic_Bobblehead'=>      1,
                'Model_Items_Generic_Cloth'     =>      1,
                'Model_Items_Generic_Electro'   =>      1,
                'Model_Items_Generic_Xmasneedles'=>     1,
                'Model_Items_Generic_Ducttape'  =>      1,
                'Model_Items_Stick'             =>      1,
                'Model_Items_Generic_Cd'        =>      5,
                'Model_Items_Generic_Led'       =>      5,
                'Model_Items_Generic_Bauble'    =>      5,
                'Model_Items_Generic_Wire'      =>      2,
        ),
        'vdrinks' => array(
                'alcohol'						=>		1,
                'Model_Items_Coffee'			=>		1,
                'Model_Items_Softdrink'			=>		4,
        ),
        'vfood' => array(
                'Model_Items_Fastfood'			=>		2,
                'Model_Items_Basefood'			=>		2,
                'Model_Items_Lunchbag'			=>		1,
        ),

    ),
    'buildings' => array(
        'Model_Places_Bar'			        => Array(	'size' =>   5,
                'content' => Array('kitchenfood' => 1, 'water' => 1, 'kitchenutils' => 1, 'alcohol' => 5, 'Model_Items_Generic_Table' => 1)
        ),
        'Model_Places_Burgerjoint'			=> Array(	'size' =>   5,
                'content' => Array('fastfood' => 4, 'kitchenutils' => 1, 'kitchenfood' => 1, 'water' => 1)
        ),
        'Model_Places_Burnedhouse'			=> Array( 	'size' =>   3,
                'content' => Array('gardening' => 3, 'diy' => 1)
        ),
        'Model_Places_House_Cellar'			=> Array( 	'size' =>   5,
                'content' => Array('diy' => 4, 'hideout' => 1)
        ),
        'Model_Places_House_Hobby'			=> Array( 	'size' =>   25,
            'content' => Array('diy' => 1, 'hideout' => 1, 'alcohol' => 2, 'Model_Items_Bandage' => 1, 'xmas' => 1)
        ),
        'Model_Places_House_Firstfloor'		=> Array( 	'size' =>   5,
                'content' => Array('kitchenutils' => 2, 'kitchenfood' => 2, 'water' => 1),
        ),
        'Model_Places_House_Secondfloor'	=> Array( 	'size' =>   5,
                'content' => Array('hideout' => 1, 'bedroom' => 1)
        ),
        'Model_Places_Constructionsite'		=> Array(	'size' =>   5,
                'content' => Array('hideout' => 1, 'diy' => 3, 'useless' => 1, 'kitchenfood' => 1)
        ),
        'Model_Places_Diy'					=> Array(	'size' =>   5,
                'content' => Array('diy' => 5, 'useless' => 1)
        ),
        'Model_Places_Radio'				=> Array(	'size' =>   5,
            'content' => Array('diy' => 5, 'useless' => 1, 'hideout' => 2, 'kitchenfood' => 1, 'ammo' => 1)
        ),
        'Model_Places_Home'					=> Array(	'size' =>   0,
                'content' => Array()
        ),
        'Model_Places_Hotel'				=> Array(	'size' =>   0,
            'content' => Array()
        ),
        'Model_Places_Treehouse'				=> Array(	'size' =>   0,
            'content' => Array()
        ),
        'Model_Places_House'				=> Array(	'size' =>   0,
            'content' => Array()
        ),
        'Model_Places_Vault'				=> Array(	'size' =>   0,
            'content' => Array()
        ),
        'Model_Places_Warehouse'			=> Array(	'size' =>   0,
            'content' => Array()
        ),
        'Model_Places_Colosseum'			=> Array(	'size' =>   0,
                'content' => Array()
        ),
        'Model_Places_Hospital'				=> Array(	'size' =>  1,
                'content' => Array('hideout' => 1, 'meds' => 1)
        ),
        'Model_Places_Hospital_Er'			=> Array(	'size' =>  20,
                'content' => Array('hideout' => 1, 'bedroom' => 1, 'smeds' => 1)
        ),
        'Model_Places_Hospital_Patients'	=> Array(	'size' =>  5,
                'content' => Array('hideout' => 2, 'bedroom' => 4, 'meds' => 1)
        ),
        'Model_Places_Hospital_Pharmacy'	=> Array(	'size' =>  15,
                'content' => Array('smeds' => 3, 'druglab' => 1, 'Model_Items_Chem' => 1)
        ),
        'Model_Places_Hospital_Morgue'	=> Array(	'size' =>  20,
            'content' => Array('smeds' => 5, 'druglab' => 1, 'Model_Items_Chem' => 2)
        ),
        'Model_Places_Hospital_Cantina'			=> Array(	'size' =>   10,
            'content' => Array('fastfood' => 2, 'kitchenutils' => 1, 'kitchenfood' => 2, 'water' => 2)
        ),
        'Model_Places_Mall'					=> Array(	'size' =>  50,
                'content' => Array('hideout' => 1, 'diy' => 1, 'useless' => 1, 'kitchenfood' => 1, 'kitchenutils' => 1, 'bedroom' => 1, 'meds' => 1, 'alcohol' => 1, 'ammo' => 1, 'weapons' => 1)
        ),
        'Model_Places_Mental'				=> Array(	'size' =>  20,
                'content' => Array('hideout' => 1, 'bedroom' => 1, 'meds' => 1, 'druglab' => 1)
        ),
        'Model_Places_Abstract_Node'		=> Array(	'size' =>  50,
                'content' => Array('useless' => 1)
        ),
        'Model_Places_Pharmacy'				=> Array(	'size' =>   3,
                'content' => Array('meds' => 3, 'druglab' => 1, 'Model_Items_Chem' => 1)
        ),
        'Model_Places_Weaponshop'			=> Array(	'size' =>   3,
                'content' => Array('ammo' => 3, 'weapons' => 1)
        ),
        'Model_Places_Store'				=> Array(	'size' =>  10,
                'content' => Array('diy' => 1, 'kitchenfood' => 2, 'kitchenutils' => 1, 'swater' => 3, 'fastfood' => 1, 'ammo' => 2, 'weapons' => 1, 'Model_Items_Pumpkin' => 1)
        ),
        'Model_Places_Junkyard'				=> Array(	'size' =>   2,
                'content' => Array('useless' => 3, 'ammo' => 2, 'gardening' => 2, 'hideout' => 1, 'diy' => 1, 'Model_Items_Generic_Plasma' => 1)
        ),
        'Model_Places_Villa'				=> Array(	'size' =>  15,
                'content' => Array('kitchenutils' => 2, 'kitchenfood' => 2, 'water' => 1, 'hideout' => 5, 'bedroom' => 2, 'diy' => 1, 'fastfood' => 1,  'Model_Items_Generic_Plasma' => 1, 'Model_Items_Generic_Pumpkin' => 1)
        ),
        'Model_Places_Cathedral'			=> Array(	'size' =>  22,
                'content' => Array('hideout' => 5, 'Model_Items_Wine' => 1)
        ),
        'Model_Places_Druglab'				=> Array(	'size' =>  10,
                'content' => Array('druglab' => 3, 'meds' => 2, 'alcohol' => 2, 'diy' => 1, 'ammo' => 2, 'weapons' => 2)
        ),
        'Model_Places_Greenhouse'			=> Array(	'size' =>   4,
                'content' => Array('water' => 5, 'swater' => 2, 'diy' => 2, 'gardening' => 3, 'Model_Items_Pumpkin' => 1)
        ),
        'Model_Places_Mausoleum'			=> Array(	'size' =>  20,
                'content' => Array('Model_Items_Coffin' => 3, 'Model_Items_Coffin2' => 1)
        ),
        'Model_Places_Plant'				=> Array(	'size' =>  8,
                'content' => Array('swater' => 4, 'water' => 2, 'diy' => 1, 'hideout' => 1, 'Model_Items_Generic_Plasma' => 1),
        ),
        'Model_Places_Camping_Tent'			=> Array(	'size' =>  2,
            'content' => Array('swater' => 3, 'hideout' => 15, 'Model_Items_Tentkit2'  =>  1,),
        ),
        'Model_Places_Camping_Grill'		=> Array(	'size' =>  10,
            'content' => Array('useless' => 5, 'alcohol' => 2, 'hideout' => 1, 'diy' => 1, 'gardening' => 1),
        ),
        'Model_Places_Camping_Office'		=> Array(	'size' =>  10,
            'content' => Array('diy' => 5, 'alcohol' => 1, 'hideout' => 1, 'gardening' => 3, 'kitchenutils' => 2),
        ),
        'Model_Places_Toilet'		        => Array(	'size' =>  5,
            'content' => Array('swater' => 5, 'diy' => 1, 'druglab' => 1, 'alcohol' => 1),
        ),
        'Model_Places_Camping'		        => Array('size' =>  10,
            'content' => Array('useless' => 1),
        ),
        'Model_Places_Asylumhideout'		=> Array(	'size' =>   0,
            'content' => Array()
        ),
    ),
);