<?php defined('SYSPATH') or die('No direct access allowed.');

return array(
	'build' => array(
		'table' => array(
            'hideout' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("hideout", "lv1");},
                'text'		=> 'Versteck errichten',
                'short'     => 'Versteck',
                'tooltip'   => 'Ermöglicht es dir, diesen Ort als Versteck zu nutzen.',
                'cat'       => 'repair_hideout',
                'energy'	=> 20,
                'requires'	=> Array('Model_Items_Generic_Wood' => 2),
                'produces'	=> Array('Model_Items_Abstract_Decay' => 100),
                'action'	=> function($location) {$location->home_extensions("hideout", "lv1", true); $location->set_decay(0);},
                'finalmsg'	=> 'Du hast so ziemlich alle Zugänge zu deinem Versteck notdürftig verbarrikadiert. Zwar ist das nur ein Anfang, aber vorerst solltest du hier sicher sein.',
            ),
            'hideoutfx1' => Array(
                'condition'	=> function($location) {return $location->home_extensions("hideout", "lv1") && ($location->get_decay() >= 0.1);},
                'text'		=> 'Versteck notdürftig reparieren',
                'short'     => 'Notdürftige Reparatur',
                'tooltip'   => 'Repariert dein Versteck, beschleunigt jedoch auch dessen Verfall.',
                'cat'       => 'repair_hideout',
                'energy'	=> 20,
                'requires'	=> Array('Model_Items_Generic_Crwood' => 3, 'Model_Items_Generic_Crmetal' => 3),
                'produces'	=> Array('Model_Items_Abstract_Decay' => 10),
                'action'	=> function($location) {$location->set_decay(-0.1, false); $location->set_patchup(0.05, false);},
                'finalmsg'	=> 'Löcher im Boden und in den Wänden? Nicht isolierte Starkstromkabel, die von der Decke hängen? Ein in Flammen stehendes Bett? Kein Problem für einen Handwerkermeister wie dich! Im Nuh ist alles notdürftig und mit minderwertigen Werkzeugen und Rohstoffen geflickt. Das wird zwar nicht allzu lange halten, aber für die nächsten paar Sekunden ist die Einsturzgefahr deines Verstecks gebannt.',
            ),
            'hideoutfx2' => Array(
                'condition'	=> function($location) {return $location->home_extensions("hideout", "lv1") && ($location->get_decay() >= 0.1);},
                'text'		=> 'Versteck gründlich reparieren',
                'short'     => 'Gründliche Reparatur',
                'tooltip'   => 'Repariert dein Versteck und reduziert den Verfall geringfügig.',
                'cat'       => 'repair_hideout',
                'energy'	=> 50,
                'requires'	=> Array('Model_Items_Generic_Wood' => 3, 'Model_Items_Generic_Metal' => 3),
                'produces'	=> Array('Model_Items_Abstract_Decay' => 15),
                'action'	=> function($location) {$location->set_decay(-0.15, false); $location->set_patchup(-0.02, false);},
                'finalmsg'	=> 'Gut, dass du hier keinen Amateur rangelassen hast. Vorsichtig und mit Augenmaß hast du alle Mängel beseitigt - das macht dein Versteck nicht nur sicherer, sondern hält auch den weiteren Verfall auf. Zumindest für eine Weile...',
            ),
            'hideoutfx3' => Array(
                'condition'	=> function($location) {return $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Schwachstellen suchen und beheben',
                'short'     => 'Ausbesserungsarbeiten',
                'tooltip'   => 'Verlangsamt den Vervall deines Verstecks stark.',
                'cat'       => 'repair_hideout',
                'energy'	=> 60,
                'requires'	=> Array('Model_Items_Generic_Wood' => 1, 'Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 3),
                'action'	=> function($location) {$location->set_patchup(-0.10, false);},
                'finalmsg'	=> 'Du hast einige Baumängel an deinem Versteck gefunden und behoben, bevor sie zum problem wurden. Das war zwar eine ziemlich anstrengende Arbeit, aber das Ergebnis war es wert!',
            ),
            'bedr1wake' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("bed", "wire") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Alarmdraht spannen',
                'short'     => 'Alarmdraht',
                'tooltip'   => 'Weckt alle schlafenden Spieler beim Eindringen von Zombies. Wird beim Einsatz zerstört.',
                'cat'       => 'hideout_bedroom',
                'energy'	=> 1,
                'requires'	=> Array('Model_Items_Generic_Wire' => 1, 'Model_Items_Generic_Crmetal' => 2),
                'action'	=> function($location) {$location->home_extensions("bed", "wire", true);},
                'finalmsg'	=> 'Dieser Alarmdraht macht ordentlich Lärm, wenn Zombies im Begriff sind, dein Versteck zu attackieren. Von jetzt an brauchst du keine Angst mehr zu haben, deinen eigenen Tod zu verschlafen.',
            ),
            'bedr1' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("bed", "lv1") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Schlafecke einrichten',
                'short'     => 'Schlafecke',
                'tooltip'   => 'Verbessert Regeneration von Energie und Müdigkeit beim Schlafen. Ermöglicht außerdem die Regeneration von Gesundheit beim Schlafen.',
                'cat'       => 'hideout_bedroom',
                'energy'	=> 5,
                'requires'	=> Array('Model_Items_Generic_Bed' => 1),
                'action'	=> function($location) {$location->home_extensions("bed", "lv1", true);},
                'finalmsg'	=> 'Endlich musst du nicht mehr auf dem Boden schlafen - mit diesem neuen Bett hat dein Versteck nun endlich die Behaglichkeit einer simplen Crackhütte gewonnen!',
			),
            'bedrlights' => Array(
                'condition'	=> function($location) {return $location->home_extensions("bed", "lv1") && !$location->home_extensions("bed", "light") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Nachtlicht installieren',
                'short'     => 'Nachtlicht',
                'tooltip'   => 'Reduziert die Einschlafzeit.',
                'cat'       => 'hideout_bedroom',
                'energy'	=> 5,
                'requires'	=> Array('Model_Items_Generic_Lamp' => 1, 'Model_Items_Energy' => 1),
                'action'	=> function($location) {$location->home_extensions("bed", "light", true);},
                'finalmsg'	=> 'Endlich brauchst du dich im Dunklen nicht mehr zu fürchten - dieses neue Nachtlicht hilft dir beim Einschlafen und vertreibt schlimme Träume.',
            ),
			'bedr2' => Array(
                'condition'	=> function($location) {return $location->home_extensions("bed", "lv1") && !$location->home_extensions("bed", "lv2") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Schlafecke kuscheliger machen',
                'short'     => 'Kuschelige Schlafecke',
                'tooltip'   => 'Verbessert Regeneration von Energie, Müdigkeit und Gesundheit beim Schlafen.',
                'cat'       => 'hideout_bedroom',
                'energy'	=> 5,
                'requires'	=> Array('Model_Items_Generic_Teddy' => 1, 'Model_Items_Generic_Cloth' => 3),
                'action'	=> function($location) {$location->home_extensions("bed", "lv2", true);},
                'finalmsg'	=> 'Mit einer Decke und einem Teddy ist dein Bett gleich viel kuscheliger. Deine Schlafecke sieht jetzt schon richtig gemütlich aus!',
			),
			'bedr3' => Array(
                'condition'	=> function($location) {return $location->home_extensions("bed", "lv2") && !$location->home_extensions("bed", "lv3") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Kingsize-Bett aufbauen',
                'short'     => 'Kingsize-Bett',
                'tooltip'   => 'Verbessert Regeneration von Energie, Müdigkeit und Gesundheit beim Schlafen.',
                'cat'       => 'hideout_bedroom',
                'energy'	=> 5,
                'requires'	=> Array('Model_Items_Generic_Bed' => 1, 'Model_Items_Generic_Cloth' => 3),
                'action'	=> function($location) {$location->home_extensions("bed", "lv3", true);},
                'finalmsg'	=> 'Dank deinem neuen KingSize-Bett hast du nun extra viel Platz, dich Nachts vor Angst in deinem Bett herumzuwälzen.',
			),
            'sofa1' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("sofa", "lv1") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Sitzecke aufstellen',
                'short'     => 'Sitzecke',
                'tooltip'   => 'Erhöht bei Benutzung die Energieregeneration. Der Effekt verstärkt sich, wenn die Sitzecke von mehreren Spielern verwendet wird.',
                'cat'       => 'hideout_bedroom',
                'energy'	=> 3,
                'requires'	=> Array('Model_Items_Abstract_Chair' => 3),
                'action'	=> function($location) {$location->home_extensions("sofa", "lv1", true);},
                'finalmsg'	=> 'Mit dieser Sitzecke kannst du dich nun endlich vernünftig entspannen ohne dich immer gleich ins Bett legen zu müssen.',
            ),
            'sofa2' => Array(
                'condition'	=> function($location) {return $location->home_extensions("sofa", "lv1") && !$location->home_extensions("sofa", "lv2") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Sesselecke aufstellen',
                'short'     => 'Sesselecke',
                'tooltip'   => 'Verbessert die Regenerationswirkung der Sitzecke. Verstärkt außerdem die Effekte beim Lesen von Büchern.',
                'cat'       => 'hideout_bedroom',
                'energy'	=> 25,
                'requires'	=> Array('Model_Items_Abstract_Chair' => 1, 'Model_Items_Generic_Bed' => 1, 'Model_Items_Generic_Cloth' => 4),
                'action'	=> function($location) {$location->home_extensions("sofa", "lv2", true);},
                'finalmsg'	=> 'Diese Sessel sehen ein wenig... eigenwillig aus. Aber zumindest sind sie bequem - mehr kann man doch nun wirklich nicht verlangen. Wobei... ein Getränkehalter wäre natürlich schön...',
            ),
			'manu1' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("manu", "base") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Werkbank aufbauen',
                'short'     => 'Werkbank',
                'tooltip'   => 'Ermöglicht die Herstellung verschiedener Gegenstände.',
                'cat'       => 'hideout_manu',
                'energy'	=> 10,
                'requires'	=> Array('Model_Items_Generic_Table' => 1, 'Model_Items_Abstract_Chair' => 1),
                'action'	=> function($location) {$location->home_extensions("manu", "base", true);},
                'finalmsg'	=> 'Ein Mann ohne Werkbank ist einfach kein richtiger Mann! (Eine Frau ohne Werkbank ist natürlich auch kein richtiger Mann.) Jetzt kannst du endlich viel Geld ausgeben und Zeug bauen, dass viel weniger kosten würde wenn du es einfach fertig kaufen würdest. Hurra!',
			),
            'manuspd' => Array(
                'condition'	=> function($location) {return $location->home_extensions("manu", "base") && $location->home_extensions("hideout", "lv1") && !$location->home_extensions("manu", "susp");},
                'text'		=> 'Halterungen anbringen',
                'short'     => 'Werkbank-Halterungen',
                'tooltip'   => 'Reduziert die benötigte Energie für alle Arbeiten an der Werkbank.',
                'cat'       => 'hideout_manu',
                'energy'	=> 15,
                'requires'	=> Array('Model_Items_Generic_Wood' => 3, 'Model_Items_Generic_Sum' => 1),
                'action'	=> function($location) {$location->home_extensions("manu", "susp", true);},
                'finalmsg'	=> 'Diese neuen Halterungen werden sich sicher als nützlich erweisen, wenn es mal etwas schweres zu heben gibt. Hoffentlich hast du beim bau nicht gepfuscht, sonst werden sie sich zusätzlich noch als tödlich erweisen...',
            ),
			'manu2' => Array(
                'condition'	=> function($location) {return $location->home_extensions("manu", "base") && !$location->home_extensions("manu", "elec") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Werkbank elektrifizieren',
                'short'     => 'Stromversorgung an der Werkbank',
                'tooltip'   => 'Schaltet zusätzliche Optionen für die Werkbank frei.',
                'cat'       => 'hideout_manu',
                'energy'	=> 10,
                'requires'	=> Array('Model_Items_Generic_Lamp' => 1, 'Model_Items_Generic_Electro' => 3, 'Model_Items_Energy' => 5),
                'action'	=> function($location) {$location->home_extensions("manu", "elec", true);},
                'finalmsg'	=> 'Ohne das Risiko tödlicher Stromschläge macht die Arbeit einfach keinen Spaß! Darum sind offene Drähte ohne Sicherung einfach ein Muss für jede Werkbank!',
			),
			'solar1' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("solar", "base") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Notstrom-Aggregat bauen',
                'short'     => 'Notstrom-Aggregat',
                'tooltip'   => 'Ermöglicht es, Strom aus Batterien zu gewinnen.',
                'cat'       => 'hideout_solar',
                'energy'	=> 15,
                'requires'	=> Array('Model_Items_Generic_Electro' => 2, 'Model_Items_Generic_Metal' => 5, 'Model_Items_Generic_Tube' => 1),
                'action'	=> function($location) {$location->home_extensions("solar", "base", true);},
                'finalmsg'	=> 'Endlich verfügst du über ein Notstrom-Aggregat, jetzt musst du nicht mehr im Dunkeln fernsehen! Yuhuu!',
			),
			'solar2' => Array(
                'condition'	=> function($location) {return $location->home_extensions("solar", "base") && !$location->home_extensions("solar", "generator") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Diesel-Generator anschließen',
                'short'     => 'Diesel-Generator',
                'tooltip'   => 'Ermöglicht es, Strom aus Energie und Benzinkanistern zu gewinnen.',
                'cat'       => 'hideout_solar',
                'energy'	=> 15,
                'requires'	=> Array('Model_Items_Generic_Motor' => 1, 'Model_Items_Generic_Sum' => 5, 'Model_Items_Generic_Metal' => 2),
                'action'	=> function($location) {$location->home_extensions("solar", "generator", true);},
                'finalmsg'	=> 'Alle paar Minuten neue Batterien einzulegen kann schon nerven. Glücklicherweise kannst du diesem Problem mit einem Kanister Benzin vorsorgen. Einziger Haken: Du brauchst einen Kanister Benzin ...',
			),
			'ktc1' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("kitchen", "base") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Küchentisch aufstellen',
                'short'     => 'Küchentisch',
                'tooltip'   => 'Ermöglicht die Herstellung verschiedener Speisen.',
                'cat'       => 'hideout_kitchen',
                'energy'	=> 5,
                'requires'	=> Array('Model_Items_Generic_Table' => 1),
                'action'	=> function($location) {$location->home_extensions("kitchen", "base", true);},
                'finalmsg'	=> 'Stolz stehst du vor deinem neuen Küchentisch; endlose kulinarische Möglichkeiten tauchen vor deinem geistigen Auge auf, verfliegen allerdings schnell wieder als dir einfällt, dass du für endlose kulinarische Möglichkeiten auch kulinarische Zutaten benötigst. Naja.... so eine verrottete Leiche lässt sich bestimmt auch fantasievoll zubereiten.',
			),
			'ktc2' => Array(
                'condition'	=> function($location) {return $location->home_extensions("kitchen", "base") && !$location->home_extensions("kitchen", "boiler") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Wasserkocher anschließen',
                'short'     => 'Wasserkocher',
                'tooltip'   => 'Schaltet zusätzliche Optionen in der Küche frei.',
                'cat'       => 'hideout_kitchen',
                'energy'	=> 2,
                'requires'	=> Array('Model_Items_Generic_Boiler' => 1),
                'action'	=> function($location) {$location->home_extensions("kitchen", "boiler", true);},
                'finalmsg'	=> 'Das zentrale Utensil jeder Küche - der Wasserkocher - steht nun auch dir zur Verfügung. Nutze ihn Weise, und missbrauche seine Kräfte nicht!',
			),
			'ktc3' => Array(
                'condition'	=> function($location) {return $location->home_extensions("kitchen", "base") && !$location->home_extensions("kitchen", "utils") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Küchenutensilien bereitstellen',
                'short'     => 'Küchenutensilien',
                'tooltip'   => 'Schaltet zusätzliche Optionen in der Küche frei.',
                'cat'       => 'hideout_kitchen',
                'energy'	=> 0,
                'requires'	=> Array('Model_Items_Generic_Mixer' => 1, 'Model_Items_Knife' => 1),
                'action'	=> function($location) {$location->home_extensions("kitchen", "utils", true);},
                'finalmsg'	=> 'ENDLICH! Nun musst du den Brei nicht mehr mit der Hand kneten und das Fleisch nicht mehr mit Karateschlägen schneiden. Heureka!',
			),
			'ktc4' => Array(
                'condition'	=> function($location) {return $location->home_extensions("kitchen", "base") && !$location->home_extensions("kitchen", "oven") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Ofen anschließen',
                'short'     => 'Ofen',
                'tooltip'   => 'Schaltet zusätzliche Optionen in der Küche frei.',
                'cat'       => 'hideout_kitchen',
                'energy'	=> 20,
                'requires'	=> Array('Model_Items_Generic_Oven' => 1),
                'action'	=> function($location) {$location->home_extensions("kitchen", "oven", true);},
                'finalmsg'	=> 'Die Zeiten von eiskaltem Essen sind vorbei! Vorrausgesetzt natürlich, du kannst etwas Strom auftreiben ...',
			),
			'defwall1' => Array(
                'condition'	=> function($location) {return ($location->get_wallstr_level() == 0) && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Tür verriegeln',
                'short'     => 'Barrikade (Tür)',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 5,
                'requires'	=> Array('Model_Items_Generic_Wood' => 1),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 5),
                'action'	=> function($location) {$location->increase_wallstrength();},
                'finalmsg'	=> 'Überlebenstipp #1 gegen Zombieinvasionen: Mach die Tür zu!',
			),
			'defwall2' => Array(
                'condition'	=> function($location) {return ($location->get_wallstr_level() == 1) && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Fenster verriegeln',
                'short'     => 'Barrikade (Fenster)',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 10,
                'requires'	=> Array('Model_Items_Generic_Wood' => 2),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 5),
                'action'	=> function($location) {$location->increase_wallstrength();},
                'finalmsg'	=> 'Überlebenstipp #2 gegen Zombieinvasionen: Eine geschlossene Tür hilft nicht viel, wenn die Fenster noch sperrangelweit offen stehen!',
			),
			'defwall3' => Array(
                'condition'	=> function($location) {return ($location->get_wallstr_level() == 2) && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Wände verstärken',
                'short'     => 'Barrikade (Wände)',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 15,
                'requires'	=> Array('Model_Items_Generic_Wood' => 2, 'Model_Items_Generic_Metal' => 1),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 5),
                'action'	=> function($location) {$location->increase_wallstrength();},
                'finalmsg'	=> 'Überlebenstipp #3 gegen Zombieinvasionen: Wenn Zombies keine Löcher in deiner Verteidigung finden, dann machen sie sich selbst welche! Verstärke also besser immer deine Wände.',
			),
			'defwall4' => Array(
                'condition'	=> function($location) {return ($location->get_wallstr_level() == 3) && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Dach verstärken',
                'short'     => 'Barrikade (Dach)',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 25,
                'requires'	=> Array('Model_Items_Generic_Wood' => 2, 'Model_Items_Generic_Metal' => 2, 'Model_Items_Generic_Sum' => 2),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 5),
                'action'	=> function($location) {$location->increase_wallstrength();},
                'finalmsg'	=> 'Überlebenstipp #4 gegen Zombieinvasionen: Wenn Zombies nicht von links, rechts, vorne und hinten kommen können, dann kommen sie eben von oben!',
			),
			'defwall5' => Array(
                'condition'	=> function($location) {return ($location->get_wallstr_level() > 3) && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Verbarrikadieren',
                'short'     => 'Barrikaden',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 50,
                'requires'	=> Array('Model_Items_Generic_Metal' => 4,'Model_Items_Generic_Table' => 2, 'Model_Items_Generic_Ducttape' => 4),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 5),
                'action'	=> function($location) {$location->increase_wallstrength();},
                'finalmsg'	=> 'Überlebenstipp #5 gegen Zombieinvasionen: Wenn alle anderen Überlebenstipps versagt haben, bist du ziemlich am Arsch. Also verbarrikadier dich lieber mit allem was du finden kannst!',
			),
			'deffence1' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("defense", "fence") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Holzzaun bauen',
                'short'     => 'Holzzaun',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 30,
                'requires'	=> Array('Model_Items_Generic_Wood' => 10, 'Model_Items_Generic_Ducttape' => 2),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 10),
                'action'	=> function($location) {$location->home_extensions("defense", "fence", true); $location->inc_defense(10);},
                'finalmsg'	=> 'Nichts hält Zombies eher ab als ein weißer, frisch lackierter Holzzaun! Glaubst du nicht? Probier es halt aus!',
			),
			'deffence2' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("defense", "fence") && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Makaberen Zaun bauen',
                'short'     => 'Makaberer Zaun',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 30,
                'requires'	=> Array('Model_Items_Bone' => 20, 'Model_Items_Generic_Ducttape' => 4),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 10),
                'action'	=> function($location) {$location->home_extensions("defense", "fence", true); $location->inc_defense(10);},
                'finalmsg'	=> 'Was tun, wenn sich die Knochen im Lagerraum langsam stapeln? Bau einen Zaun damit! Das ist eine gute Beschäftigungstherapie und sieht einfach megacool aus. Achja, Zombies kannst du auf die Art auch von deinem Rasen fernhalten.',
			),
            'deftrench' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("defense", "trench") && $location->home_extensions("hideout", "lv1") && !$location->home_extensions("limits", "notrench");},
                'text'		=> 'Graben buddeln',
                'short'     => 'Graben',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 95,
                'requires'	=> Array(),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 15),
                'action'	=> function($location) {$location->home_extensions("defense", "trench", true); $location->inc_defense(15);},
                'finalmsg'	=> 'Puuh, endlich fertig. Es war ein hartes Stück Arbeit, aber du hast es geschafft einen mehrere Meter tiefen Graben um das Versteck zu schaufeln. Den werden die Zombies niemals überwinden können - es sei denn, es fallen genug Zombies hinein, dass die restlichen einfach drüberlaufen können...',
            ),
            'deftrench2' => Array(
                'condition'	=> function($location) {return !$location->home_extensions("defense", "watertrench") && $location->home_extensions("defense", "trench") && $location->home_extensions("hideout", "lv1") && !$location->home_extensions("limits", "notrench");},
                'text'		=> 'Graben füllen',
                'short'     => 'Wassergraben',
                'tooltip'   => 'Verstärkt die Verteidigung des Verstecks.',
                'cat'       => 'hideout_defense',
                'energy'	=> 2,
                'requires'	=> Array('Model_Items_Generic_Waterv' => 25),
                'produces'	=> Array('Model_Items_Abstract_Defense' => 100),
                'achievement' => Model_Achievement::MA_LORD,
                'action'	=> function($location) {$location->home_extensions("defense", "watertrench", true); $location->inc_defense(100);},
                'finalmsg'	=> 'Nun, da dein Graben voller Wasser ist, bist du praktisch vor Zombieangriffen geschützt - solange du dein Versteck nicht verlässt, versteht sich.',
            ),
			'defimp' => Array(
                'condition'	=> function($location) {return ($location->get_impaler_level() == 0) && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Fallgruben anlegen',
                'short'     => 'Fallgruben',
                'tooltip'   => 'Ermöglicht es, einmal pro Belagerung eine große Menge Zombies zu vernichten. Muss nach dem Einsatz durch Verlassen des verstecks reaktiviert werden.',
                'cat'       => 'hideout_defense',
                'energy'	=> 40,
                'requires'	=> Array('Model_Items_Generic_Wood' => 2, 'Model_Items_Generic_Tube' => 5, 'Model_Items_Generic_Sum' => 1, 'Model_Items_Generic_Metal' => 1),
                'action'	=> function($location) {$location->defb_ready_impaler();},
                'finalmsg'	=> 'Nichts ist befriedigender als das Geräusch von verfaulendem Fleisch, dass auf Holzpfähle gespießt wird!',
			),
			'defbat' => Array(
                'condition'	=> function($location) {return ($location->get_batgun_level() == 0) && $location->home_extensions("hideout", "lv1");},
                'text'		=> 'Stationäres Batteriegeschütz aufbauen',
                'short'     => 'Stationäres Batteriegeschütz',
                'tooltip'   => 'Ermöglicht es, bei einer Belagerung Zombies durch Batterien zu töten.',
                'cat'       => 'hideout_defense',
                'energy'	=> 20,
                'requires'	=> Array('Model_Items_Generic_Sum' => 1, 'Model_Items_Generic_Tube' => 2, 'Model_Items_Generic_Metal' => 1),
                'action'	=> function($location) {$location->defb_ready_batgun();},
                'finalmsg'	=> 'Say hello to my little friend!',
			),
		)	
	),
		
	'kitchen' => array(
		'table' => array(
			'soft' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'kitchen',
					'environment' => Array("base"),
					'text' => 'Softdrinks zusammenkippen',
					'energy' => 1,
					'requires' => Array('Model_Items_Softdrink' => 2),
					'produces' => Array('Model_Items_Generic_Water0' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Nur wenige wissen, dass sich Softdrinks in klares Wasser umwandeln lassen, indem man einfach zwei von ihnen zusammenmischt. Gut, dass du in Chemie immer so gut aufgepasst hast!',
			),
			'body' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'kitchen',
					'environment' => Array("base", "utils"),
					'text' => 'Leiche ausnehmen',
                    'short'     => 'Ausgenommene Leiche',
					'energy' => 15,
					'requires' => Array('Model_Items_Body' => 1),
					'produces' => Array('Model_Items_Rawmeat' => 8, 'Model_Items_Generic_Waterb' => 3),
					'achievement' => Model_Achievement::MA_BLOODSUCKER,
					'finalmsg'	=> 'Du benutzt deine Machete, um die Leiche in kleine Stücke zu schneiden. Das macht sie zwar nicht genießbarer, aber zumindest handlicher.',
			),
            'body2' => Array(
                    'obvious' => true,
                    'keys' => null,
                    'base' => 'kitchen',
                    'environment' => Array("base", "cursed"),
                    'text' => 'Leiche zersägen',
                    'short'     => 'Zersägte Leiche',
                    'energy' => 30,
                    'requires' => Array('Model_Items_Body' => 1),
                    'produces' => Array('Model_Items_Fleshfood' => 12, 'Model_Items_Generic_Waterb' => 1),
                    'achievement' => Model_Achievement::MA_BLOODSUCKER,
                    'finalmsg'	=> 'Du benutzt deine Machete, um die Leiche in kleine Stücke zu schneiden. Das macht sie zwar nicht genießbarer, aber zumindest handlicher.',
            ),
			'meat' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'kitchen',
					'environment' => Array("base", "oven"),
					'text' => 'Knochen mit Fleisch abkochen',
					'energy' => 10,
					'requires' => Array('Model_Items_Rawmeat' => 4, 'Model_Items_Energy' => 2),
					'produces' => Array('Model_Items_Rawmeat2' => 4),
					'achievement' => null,
					'finalmsg'	=> 'Nachdem du die Knochen mit Fleisch in den Ofen gelegt hast, ist deine Küche erfüllt von .... leckerem .... Geruch. Aber wenigstens kannst du die Knochen nun essen, ohne dir eine Vergiftung zuzuziehen.',
			),
			'coffee' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'kitchen',
					'environment' => Array("base", "boiler"),
					'text' => 'Kaffee kochen',
					'energy' => 0,
					'requires' => Array('Model_Items_Coffee' => 1, 'Model_Items_Energy' => 2),
					'produces' => Array('Model_Items_Coffee2' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Erschöpft vom Zombieapokalypse-Alltag setzt du dir erstmal eine schöne Kanne Kaffee auf.',
			),
			'water' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'kitchen',
					'environment' => Array("base", "boiler"),
					'text' => 'Wasser abkochen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Waterv' => 1, 'Model_Items_Energy' => 2),
					'produces' => Array('Model_Items_Generic_Water0' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Das Wasser in deiner Flasche schaut dich mit großen, traurigen Augen an - aber das hilft nicht viel. Eiskalt kochst du es auf 100° und tötest so alles Leben darin ab!',
			),
			'nom1' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'kitchen',
					'environment' => Array("base", "utils"),
					'text' => 'Leckere Speise zusammenstellen',
					'energy' => 10,
					'requires' => Array('Model_Items_Basefood' => 2),
					'produces' => Array('Model_Items_Nom' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Wenn man zwei Grundnahrungsmittel kombiniert, kann man unter umständen ein ganz neues Nahrungsmittel erschaffen. Diesen Vorgang nennt man "kochen", und du hast ihn soeben erfolgreich durchgeführt.',
			),
			'nom2' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'kitchen',
					'environment' => Array("base", "oven"),
					'text' => 'Leckere Speise verfeinern',
					'energy' => 10,
					'requires' => Array('Model_Items_Nom' => 1, 'Model_Items_Generic_Spice' => 1, 'Model_Items_Energy' => 1),
					'produces' => Array('Model_Items_Nom2' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Eine leckere Speise ist nur halb so gut, wenn sie kalt und ungewürzt ist. Du streust also ein paar Gewürze drüber und lässt das ganze eine Weile im Ofen schmoren - voilá, du hast deine Speise noch leckerer gemacht!',
			),
            'pksoup' => Array(
                    'obvious' => true,
                    'keys' => null,
                    'base' => 'kitchen',
                    'environment' => Array("base"),
                    'text' => 'Kürbissuppe herstellen',
                    'energy' => 10,
                    'requires' => Array('Model_Items_Pumpkin' => 1, 'Model_Items_Generic_Spice' => 1, 'Model_Items_Generic_Waterv' => 1),
                    'produces' => Array('Model_Items_Pumpkinsoup' => 5),
                    'achievement' => null,
                    'finalmsg'	=> 'Zerstampfen, verrühren, würzen. Für dieses Rezept muss man kein Meisterkoch sein, und man kann es in allen Lebenslagen anwenden (Kürbisse zubereiten, Gespräche mit dem Finanzamt etc) ',
            ),
            'fsoup' => Array(
                    'obvious' => true,
                    'keys' => null,
                    'base' => 'kitchen',
                    'environment' => Array("base", "cursed"),
                    'text' => 'Suppe aus "Tomaten" herstellen',
                    'energy' => 8,
                    'requires' => Array('Model_Items_Fleshfood' => 6, 'Model_Items_Generic_Waterb' => 1),
                    'produces' => Array('Model_Items_Fleshsoup' => 1),
                    'achievement' => null,
                    'finalmsg'	=> 'Nicht daran denken was du hier gerade tust... nicht daran denken was du hier gerade tust... nicht daran denken was du hier gerade tust...',
            ),
			'xmas1' => Array(
					'obvious' => false,
					'keys' => Array("Model_Items_Generic_Cookieproto"),
					'base' => 'kitchen',
					'environment' => Array("base", "utils"),
					'text' => 'Plätzchen backen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Cookieproto' => 1),
					'produces' => Array('Model_Items_Cookie' => 5),
					'achievement' => null,
					'finalmsg'	=> 'Ein weihnachtlicher Durft erfüllt dein Versteck, als du kleine Figürchen aus dem Teig presst und diese zu Plätzchen backst.',
			),
			'xmas2' => Array(
					'obvious' => false,
					'keys' => Array("Model_Items_Generic_Cookieproto"),
					'base' => 'kitchen',
					'environment' => Array("base", "utils"),
					'text' => 'Besondere Plätzchen backen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Cookieproto' => 1, 'Model_Items_Powderpack' => 1),
					'produces' => Array('Model_Items_Cookie2' => 5),
					'achievement' => null,
					'finalmsg'	=> 'Normale Plätzchen sind langweilig, also fügst du ein paar kreative Extra-Zutaten hinzu...',
			),
		)	
	),
		
	'power' => array(
		'table' => array(
			'bat1' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'solar',
                'environment' => Array("base"),
                'text' => '1 mAh aus Batterien erzeugen',
                'energy' => 0,
                'requires' => Array('Model_Items_Battery' => 2),
                'produces' => Array('Model_Items_Energy' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Es werde Licht! Herzlichen Glückwunsch, du hast etwas Strom für dein Versteck erzeugt!',
			),
			'bat2' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'solar',
                'environment' => Array("base"),
                'text' => '2 mAh aus Batterien erzeugen',
                'energy' => 0,
                'requires' => Array('Model_Items_Battery' => 4),
                'produces' => Array('Model_Items_Energy' => 2),
                'achievement' => null,
                'finalmsg'	=> 'Es werde Licht! Herzlichen Glückwunsch, du hast etwas Strom für dein Versteck erzeugt!',
			),
			'bat3' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'solar',
                'environment' => Array("base"),
                'text' => '5 mAh aus Batterien erzeugen',
                'energy' => 0,
                'requires' => Array('Model_Items_Battery' => 10),
                'produces' => Array('Model_Items_Energy' => 5),
                'achievement' => null,
                'finalmsg'	=> 'Es werde Licht! Herzlichen Glückwunsch, du hast etwas Strom für dein Versteck erzeugt!',
			),
			'bat4' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'solar',
					'environment' => Array("base"),
					'text' => 'Batterie überladen',
					'energy' => 0,
					'requires' => Array('Model_Items_Battery' => 1, 'Model_Items_Energy' => 2),
					'produces' => Array('Model_Items_Generic_Supercharger' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Wer glaubt schon an Herstellerangaben! Diese Batterie kann problemlos so stark aufgeladen werden, dass man damit eine Kleinstadt mehrere Tage mit Strom versorgen könnte. Und diese Gerüchte von wegen "Explosionsgefahr" sind bestimmt bloß Panikmache aus den Medien ...',
			),
			'bat5' => Array(
					'obvious' => false,
					'keys' => Array('Model_Items_Generic_Supercharger'),
					'base' => 'solar',
					'environment' => Array("base"),
					'text' => '2 mAh aus Supercharger erzeugen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Supercharger' => 1),
					'produces' => Array('Model_Items_Energy' => 2),
					'achievement' => null,
					'finalmsg'	=> 'Es werde Licht! Herzlichen Glückwunsch, du hast etwas Strom für dein Versteck erzeugt!',
			),
			'gas1' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'solar',
					'environment' => Array("generator"),
					'text' => '10 mAh aus Benzin erzeugen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Jerrycan' => 1),
					'produces' => Array('Model_Items_Energy' => 10),
					'achievement' => null,
					'finalmsg'	=> 'Es werde Licht! Herzlichen Glückwunsch, du hast etwas Strom für dein Versteck erzeugt!',
			),
			'hand1' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'solar',
					'environment' => Array("generator"),
					'text' => '1 mAh mit Muskelkraft erzeugen',
					'energy' => 45,
					'requires' => Array(),
					'produces' => Array('Model_Items_Energy' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Es werde Licht! Herzlichen Glückwunsch, du hast etwas Strom für dein Versteck erzeugt!',
			),
			'hand2' => Array(
					'obvious' => true,
					'keys' => null,
					'base' => 'solar',
					'environment' => Array("generator"),
					'text' => '2 mAh mit Muskelkraft erzeugen',
					'energy' => 90,
					'requires' => Array(),
					'produces' => Array('Model_Items_Energy' => 2),
					'achievement' => null,
					'finalmsg'	=> 'Es werde Licht! Herzlichen Glückwunsch, du hast etwas Strom für dein Versteck erzeugt!',
			),
		)
	),
		
	'workshop' => array(

        'table' => array(
            'bike' => Array(
                'obvious' => false,
                'cat' => 'fix',
                'keys' => ['Model_Items_Generic_Bike'],
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Fahrrad reparieren',
                'short'     => 'Fahrrad',
                'energy' => 15,
                'requires' => Array('Model_Items_Generic_Bike' => 1, 'Model_Items_Generic_Sum' => 2, 'Model_Items_Generic_Belt' => 1),
                'produces' => Array('Model_Items_Generic_Bike2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Das war einfacher als du dachtest - dein Fahrrad ist nun wieder einsatzbereit!',
            ),
			'srv_sum' => Array(
                'condition' => function($l) {global $player; return $player->job(1060);},
                'obvious' => true,
                'cat' => 'create',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Selbstgebaute Kleinteile herstellen',
                'energy' => 25,
                'requires' => Array('Model_Items_Generic_Crmetal' => 5),
                'produces' => Array('Model_Items_Generic_Sum' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Großartig - andere hätten diese Kleinteile mühsam zusammensuchen müssen, du kannst sie einfach selbst herstellen!',
			),
			'srv_mat' => Array(
                'condition' => function($l) {global $player; return $player->job(1060);},
                'obvious' => true,
                'cat' => 'create',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Flickenmatratze herstellen',
                'energy' => 25,
                'requires' => Array('Model_Items_Generic_Cloth' => 8),
                'produces' => Array('Model_Items_Generic_Bed' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Keine Ahnung wozu du als Survivalist überhaupt eine Matratze brauchst... aber gut, wenn du Spaß an Bastelarbeit hast.',
			),
			'srv_tbl' => Array(
                'condition' => function($l) {global $player; return $player->job(1060);},
                'obvious' => true,
                'cat' => 'create',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Provisorischen Tisch herstellen',
                'energy' => 25,
                'requires' => Array('Model_Items_Generic_Wood' => 7),
                'produces' => Array('Model_Items_Generic_Table' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Wer braucht schon EKEA? Dieser Tisch hat eine mindestens genauso fragwürdige Qualität, und er ist aus echtem undefinierbaren Holz!.',
			),
			'tech' => Array(
                'condition' => function($l) {global $player; return $player->job(3030);},
                'obvious' => true,
                'cat' => 'assemble',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Lasermessgerät herstellen',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 1, 'Model_Items_Generic_Tube' => 1),
                'produces' => Array('Model_Items_Generic_Lasermapper' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Wer braucht schon EKEA? Dieser Tisch hat eine mindestens genauso fragwürdige Qualität, und er ist aus echtem undefinierbaren Holz!.',
			),
			'crwood' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Holzbrett herstellen',
                'energy' => 6,
                'requires' => Array('Model_Items_Generic_Crwood' => 4),
                'produces' => Array('Model_Items_Generic_Wood' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Gäbe es einen Gott für Recycling, er wäre sicherlich stolz auf dich!',
			),
			'crmetal' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Altmetall herstellen',
                'energy' => 6,
                'requires' => Array('Model_Items_Generic_Crmetal' => 4),
                'produces' => Array('Model_Items_Generic_Metal' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Gäbe es einen Gott für Recycling, er wäre sicherlich stolz auf dich!',
			),
			'crwood2' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'create',
                'environment' => Array("elec"),
                'text' => 'Holzbrett effizient herstellen',
                'energy' => 0,
                'requires' => Array('Model_Items_Generic_Crwood' => 4, 'Model_Items_Energy' => 2),
                'produces' => Array('Model_Items_Generic_Wood' => 3),
                'achievement' => null,
                'finalmsg'	=> 'Gäbe es einen Gott für Recycling, er wäre sicherlich enorm stolz auf dich!',
			),
			'crmetal2' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("elec"),
                'text' => 'Altmetall effizient herstellen',
                'energy' => 0,
                'requires' => Array('Model_Items_Generic_Crmetal' => 4, 'Model_Items_Energy' => 2),
                'produces' => Array('Model_Items_Generic_Metal' => 3),
                'achievement' => null,
                'finalmsg'	=> 'Gäbe es einen Gott für Recycling, er wäre sicherlich enorm stolz auf dich!',
			),
            'bolts1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Bolzen fertigen',
                'energy' => 2,
                'requires' => Array('Model_Items_Generic_Crwood' => 1),
                'produces' => Array('Model_Items_Bolts' => 3),
                'achievement' => null,
                'finalmsg'	=> 'Wäre dies ein Vampirspiel, so wärst du mit diesen Bolzen perfekt ausgerüstet, um Dracula gegenüber zu treten. Leider ist dies ein Zombiespiel, also wirst du wohl doch zur Armbrust greifen müssen...',
            ),
            'bolts2' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Bolzen fertigen',
                'energy' => 3,
                'requires' => Array('Model_Items_Generic_Wood' => 1),
                'produces' => Array('Model_Items_Bolts' => 10),
                'achievement' => null,
                'finalmsg'	=> 'Wäre dies ein Vampirspiel, so wärst du mit diesen Bolzen perfekt ausgerüstet, um Dracula gegenüber zu treten. Leider ist dies ein Zombiespiel, also wirst du wohl doch zur Armbrust greifen müssen...',
            ),
			'bbag1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Leichensack herstellen',
                'energy' => 15,
                'requires' => Array('Model_Items_Generic_Cloth' => 8),
                'produces' => Array('Model_Items_Bodybag' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Ein Stich hier.... ein Stich dort... Fertig! Dieser stylische Leichensack wird deine Transportprobleme zumindest im Bezug auf Leichen für immer lösen!',
			),
			'bbag2' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Bodybag4'),
                'cat' => 'fix',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Leichensack provisorisch flicken',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Cloth' => 3, 'Model_Items_Bodybag4' => 1),
                'produces' => Array('Model_Items_Bodybag2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Du fühlst sich wie eine Art makabrer Modedesigner! Ein paar Sticke mit der Nadel, schon ist dieser hässliche Riss fast nicht mehr zu sehen.',
			),
			'bbag3' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Bodybag4'),
                'base' => 'manu',
                'cat' => 'fix',
                'environment' => Array("base"),
                'text' => 'Leichensack gründlich flicken',
                'energy' => 9,
                'requires' => Array('Model_Items_Generic_Cloth' => 5, 'Model_Items_Bodybag4' => 1),
                'produces' => Array('Model_Items_Bodybag' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Du fühlst sich wie eine Art makabrer Modedesigner! Ein paar Sticke mit der Nadel, schon ist dieser hässliche Riss nicht mehr zu sehen. Und ein paar potentielle Schwachstellen hast du gleich mit ausgebessert! Bravo!',
			),
			'skel' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Generic_Bone3'),
                'cat' => 'disassemble',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Knochen sortieren',
                'short'     => 'Sortierte Knochen',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Bone3' => 1),
                'produces' => Array('Model_Items_Bone' => 8, 'Model_Items_Bone2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Endlich kannst du deine destruktiven Energien mal an was anderem als an Zombies ausleben. Aus irgend einem Grund bereitet dir das Auseinandernehmen dieses Skeletts eine merkwürdige Befriedigung...',
			),
            'bat1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Schläger aufpeppen',
                'energy' => 20,
                'requires' => Array('Model_Items_Bat' => 1, 'Model_Items_Generic_Ducttape' => 2, 'Model_Items_Generic_Crmetal' => 4),
                'produces' => Array('Model_Items_Bat2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit diesem Schläger fährst du keine Homerun-Rekorde mehr ein... Dafür ist er wesentlich Effektiver im Bereich "Zombieverstümmelung".',
            ),
            'crossbow' => Array(
                'obvious' => true,
                'cat' => 'assemble',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Armbrust herstellen',
                'energy' => 50,
                'requires' => Array('Model_Items_Generic_Wire' => 1, 'Model_Items_Generic_Wood' => 2, 'Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 1),
                'produces' => Array('Model_Items_Crossbow' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Du hast eine Armbrust hergestellt. Wie wärs, wenn du direkt mal mit Zielübungen auf ein paar Zombies beginnst?',
            ),
			'batgun1' => Array(
                'obvious' => true,
                'keys' => Array('Model_Items_Batgun'),
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Ladevorrichtung des Batteriewerfers verbessern',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Ducttape' => 1, 'Model_Items_Generic_Tube' => 1, 'Model_Items_Batgun' => 1),
                'produces' => Array('Model_Items_Batgun2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit ein paar kleinen Verbesserungen kann man die Effektivität eines Batteriewerfers ungemein erhöhen. Mit der neuen Ladevorrichtung sparst du im Kampf viel Zeit, die du wiederum in das Abschlachten weiterer Zombies investieren kannst.',
			),
			'batgun2' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Batgun2'),
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("elec"),
                'text' => 'Batteriewerfer zum Mark II umbauen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Pressure' => 1, 'Model_Items_Generic_Sum' => 2, 'Model_Items_Generic_Tube' => 1, 'Model_Items_Batgun2' => 1),
                'produces' => Array('Model_Items_Batgun3' => 1),
                'achievement' => Model_Achievement::MA_BUILD_MKII,
                'finalmsg'	=> 'Mit ein paar kleinen Verbesserungen kann man die Effektivität eines Batteriewerfers ungemein erhöhen. Der neue Druckregler passt die Abschussgeschwindigkeit genau der Entfernung an und erhöht so deine Treffsicherheit. Mit ein wenig Glück kannst du mit einer Baterie sogar zwei Zombies erwischen!',
			),
            'aquagun1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("elec"),
                'text' => 'Wasserpistole verbessern',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Pressure' => 1, 'Model_Items_Generic_Sum' => 1, 'Model_Items_Generic_Tube' => 4, 'Model_Items_Watergun' => 1),
                'produces' => Array('Model_Items_Watergun2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Es ist wirklich überhaupt nicht bizarr, wenn erwachsene Überlebende einer Apokalypse durch die Ruinen der Zivilisation rennen und mit militärischen Wasserpistolen um sich spritzen! Hört auch zu lachen!',
            ),
            'splintergun1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("elec"),
                'text' => 'Splitterwerfer zum Mark II umbauen',
                'energy' => 25,
                'requires' => Array('Model_Items_Generic_Pressure' => 1, 'Model_Items_Generic_Sum' => 2, 'Model_Items_Generic_Tube' => 1, 'Model_Items_Generic_Metal' => 3, 'Model_Items_Splintergun' => 1),
                'produces' => Array('Model_Items_Splintergun2' => 1),
                'achievement' => Model_Achievement::MA_BUILD_MKII,
                'finalmsg'	=> 'Was kann man mit einer verrückten Waffe machen? Sie NOCH verrückter machen, natürlich! Was denn sonst?',
            ),
            'clothes_impr' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Kleidung verbessern',
                'energy' => 15,
                'requires' => Array('Model_Items_Clothes' => 1, 'Model_Items_Generic_Cloth' => 1, 'Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Crmetal' => 4),
                'produces' => Array('Model_Items_Clothes2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Normalerweise würde kein Mensch so etwas machen - aber in der aktuellen Situation ist es tatsächlich notwendig, seine Bequemlichkeit zugunsten von etwas mehr Sicherheit zu opfern.',
            ),
            'clothes_fix' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'fix',
                'environment' => Array("base"),
                'text' => 'Kleidung nähen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Clothes' => 1, 'Model_Items_Generic_Cloth' => 2),
                'produces' => Array('Model_Items_Clothes' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Es sieht etwas zusammengeschustert aus... aber wenigstens musst du nun nicht mehr in Unterwäsche herumlaufen.',
            ),
            'shield' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'assemble',
                'environment' => Array("base"),
                'text' => 'Einfachen Holzkistendeckel bauen',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Wood' => 4, 'Model_Items_Generic_Ducttape' => 1),
                'produces' => Array('Model_Items_Shield' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Hierfür muss man wahrlich kein Meister der Handwerkskunst sein. Du hast einen Holzkistendeckel zusammengebaut.',
            ),
            'shield2' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Holzkistendeckel stabilisieren',
                'energy' => 20,
                'requires' => Array('Model_Items_Shield' => 1, 'Model_Items_Generic_Wood' => 4, 'Model_Items_Generic_Sum' => 1),
                'produces' => Array('Model_Items_Shield2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit ein bisschen mehr Holz (und Schrauben anstelle von Klebeband) hast du deinen Holzkistendeckel stabilisiert.',
            ),
            'helmet' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'upgrade',
                'environment' => Array("base"),
                'text' => 'Fahrradhelm verbessern',
                'energy' => 20,
                'requires' => Array('Model_Items_Helmet' => 1, 'Model_Items_Generic_Metal' => 4, 'Model_Items_Generic_Sum' => 1),
                'produces' => Array('Model_Items_Helmet2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit ein bisschen Metall (und Schrauben anstelle von Klebeband) hast du deinen Fahrradhelm verbessert.',
            ),
			'ripbed' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("base"),
                'text' => 'Matratze auseinanderschneiden',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Bed' => 1),
                'produces' => Array('Model_Items_Generic_Cloth' => 5),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'ripboil' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("base"),
                'text' => 'Wasserkocher auseinandernehmen',
                'short'     => 'Wasserkocher-Bauteile',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Boiler' => 1),
                'produces' => Array('Model_Items_Generic_Crmetal' => 1, 'Model_Items_Generic_Electro' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'ripmix' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("base"),
                'text' => 'Handmixer auseinandernehmen',
                'short'     => 'Handmixer-Bauteile',
                'energy' => 6,
                'requires' => Array('Model_Items_Generic_Mixer' => 1),
                'produces' => Array('Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 2),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'riptable' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("base"),
                'text' => 'Järpentisch auseinandernehmen',
                'short'     => 'Järpen-Bauteile',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Table' => 1),
                'produces' => Array('Model_Items_Generic_Wood' => 5, 'Model_Items_Generic_Sum' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'rippressure' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("elec"),
                'text' => 'Druckregler auseinandernehmen',
                'short'     => 'Druckregler-Bauteile',
                'energy' => 30,
                'requires' => Array('Model_Items_Generic_Pressure' => 1),
                'produces' => Array('Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 3, 'Model_Items_Generic_Tube' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'ripmotor' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("elec"),
                'text' => 'Motor auseinandernehmen',
                'short'     => 'Motor-Bauteile',
                'energy' => 50,
                'requires' => Array('Model_Items_Generic_Motor' => 1),
                'produces' => Array('Model_Items_Generic_Metal' => 7, 'Model_Items_Generic_Electro' => 3, 'Model_Items_Generic_Tube' => 5),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'ripoven' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("elec"),
                'text' => 'Ofen auseinandernehmen',
                'short'     => 'Ofen-Bauteile',
                'energy' => 50,
                'requires' => Array('Model_Items_Generic_Oven' => 1),
                'produces' => Array('Model_Items_Generic_Metal' => 5, 'Model_Items_Generic_Sum' => 5, 'Model_Items_Generic_Cloth' => 2),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'pbomb' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'assemble',
                'environment' => Array("base"),
                'text' => 'Schwarzpulverbombe bauen',
                'energy' => 1,
                'requires' => Array('Model_Items_Generic_Ducttape' => 1, 'Model_Items_Generic_Gunpowder' => 1, 'Model_Items_Generic_Plasticbag' => 1),
                'produces' => Array('Model_Items_Powderbomb' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Vorsichtig füllst du das Schwarzpulver in eine Plastiktüte... BINGO! Perfekte Schwarzpulverbombe! Dieses Teil wird dir sicher irgendwann einmal das Leben retten.',
			),
			'halloween' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Generic_Pumpkin'),
                'base' => 'manu',
                'cat' => 'assemble',
                'environment' => Array("base"),
                'text' => 'Kürbisbombe bauen',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Pumpkin' => 1, 'Model_Items_Generic_Gunpowder' => 5),
                'produces' => Array('Model_Items_Pumpkinbomb' => 1),
                'achievement' => Model_Achievement::MA_PUMPKINHEAD,
                'finalmsg'	=> 'So ein Kürbis kann sicher toll explodieren, wenn man ihn bis zum Rand mit Schwarzpulver vollstopft! Und das Gesicht.... naja, der Kürbis hätt halt ohne einfach doof ausgesehen.',
			),
            'bandage' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'assemble',
                'environment' => Array("base"),
                'text' => 'Provisorische Bandage herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Cloth' => 2, 'Model_Items_Whiskey' => 1),
                'produces' => Array('Model_Items_Bandage2' => 1, 'Model_Items_Smallbottle' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Also, so richtig hygienisch sieht das jetzt nicht aus...',
            )
		)
	),
	
	'lda' => array(
		'Model_Places_Burgerjoint' => array(
			'body' => Array(
					'obvious' => true,
					'keys' => null,
					'text' => 'Leiche frittieren',
					'energy' => 15,
					'requires' => Array('Model_Items_Body' => 1, 'Model_Items_Generic_Supercharger' => 2),
					'produces' => Array('Model_Items_Bodycrisp' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Alles wird leckerer, wenn man es frittiert - das wusste schon Homer Simpson. Jetzt gilt es herauszufinden, ob das auch mit Leichen funktioniert...',
			),
			'coffee' => Array(
					'obvious' => true,
					'keys' => null,
					'text' => 'Kaffee kochen',
					'energy' => 0,
					'requires' => Array('Model_Items_Coffee' => 1, 'Model_Items_Generic_Supercharger' => 1),
					'produces' => Array('Model_Items_Coffee2' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Erschöpft vom Zombieapokalypse-Alltag setzt du dir erstmal eine schöne Kanne Kaffee auf.',
			),
			'water' => Array(
					'obvious' => true,
					'keys' => null,
					'text' => 'Wasser abkochen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Waterv' => 1, 'Model_Items_Generic_Supercharger' => 1),
					'produces' => Array('Model_Items_Generic_Water0' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Das Wasser in deiner Flasche schaut dich mit großen, traurigen Augen an - aber das hilft nicht viel. Eiskalt kochst du es auf 100° und tötest so alles Leben darin ab!',
			),
		),
		'Model_Places_Weaponshop' => array(
			'machete' => Array(
					'obvious' => false,
					'keys' => Array('Model_Items_Machete'),
					'text' => 'Machete schleifen',
					'energy' => 25,
					'requires' => Array('Model_Items_Machete' => 1),
					'produces' => Array('Model_Items_Machete2' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Deine Machete sieht schon ziemlich stumpf und rostig aus, also bringst du sie mit diesem praktischen Schleifstein wieder auf Vordermann.',
			),
			'bnmachete' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Machete verbessern',
					'energy' => 15,
					'requires' => Array('Model_Items_Machete2' => 1, 'Model_Items_Bandage' => 1, 'Model_Items_Generic_Ducttape' => 2),
					'produces' => Array('Model_Items_Macheteband' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Du nimmst die Bandage, wickelst die um den Griff der Machete und befestigst die Enden mit ein wenig Klebeband. Toll, nun kannst du deine Machete viel einfacher halten und es besteht keine Gefahr mehr, beim Metzeln (oder bei der Intimrasur) abzurutschen.',
			),
			'dlmachete' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Coole Machetenposen üben',
					'energy' => 5,
					'requires' => Array('Model_Items_Machete2' => 2),
					'produces' => Array('Model_Items_Macheteduo' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Wenn du schon ganz allein gegen Zombies kämpfen musst, kannst du dabei wenigstens cool aussehen. Leider ist niemand mehr da, um ein Video von deiner coolen neuen Choreographie bei YouTube zu posten.',
			),
			'plasma' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Plasmakanone bauen',
					'energy' => 60,
					'requires' => Array('Model_Items_Generic_Plasma' => 1, 'Model_Items_Generic_Electro' => 1, 'Model_Items_Handgun' => 1, 'Model_Items_Batgun' => 1),
					'produces' => Array('Model_Items_Plasmagun' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Gut, dass dieser hochgradig experimentelle Plasmablitz-Generator eine absolut standartkonforme Bauform sowie Anschlüsse besitzt, sodass du ihn mit Bauteilen deines Batteriewerfers und Revolvers in eine tödliche Waffe verwandeln kannst. Fast könnte man meinen, das ganze wäre ziemlich unrealistisch.... aber nur fast!',
			),
			'splbatgun' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Batteriewerfer pimpen',
					'energy' => 5,
					'requires' => Array('Model_Items_Generic_Pressure' => 3, 'Model_Items_Generic_Sum' => 1, 'Model_Items_Batgun2' => 1),
					'produces' => Array('Model_Items_Batgunsplat' => 1),
					'finalmsg'	=> 'Viel hilft viel - mit ein paar zusätzlichen Druckreglern kannst du Batterien nun mit extra-hoher Geschwindigkeit abfeuern.',
			),
			'snpbatgun' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Scharfschützen-Batteriewerfer bauen',
					'energy' => 5,
					'requires' => Array('Model_Items_Generic_Tube' => 5, 'Model_Items_Generic_Sum' => 2, 'Model_Items_Batgun2' => 1),
					'produces' => Array('Model_Items_Batgunsnp' => 1),
					'finalmsg'	=> 'Verlängerter Lauf: Check. Feinjustierte Abschussvorrichtung: Check. Rosa glitzernder Ponyaufkleber: Check. Tötungsmaschine: Bereit!',
			),
			'ammo' => Array(
					'obvious' => true,
					'keys' => null,
					'text' => 'Munition produzieren',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Tube' => 1, 'Model_Items_Generic_Gunpowder' => 1),
					'produces' => Array('Model_Items_Ammo' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Anscheinend kann man sich Munition ganz einfach selber bauen, indem man ein Kupferrohr in kleine Stücke sägt und mit Schwarzpulver füllt. Wer hätte das gedacht?',
			),
		),
        'Model_Places_Camping_Grill' => array(
            'grill1' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Leiche grillen',
                'energy' => 10,
                'requires' => Array('Model_Items_Body' => 1),
                'produces' => Array('Model_Items_Steak' => 3),
                'achievement' => null,
                'finalmsg'	=> 'Mit einem Grill kannst du selbst das ekelhafteste Zeug schmackhaft machen. Herzlichen Glückwunsch, du hast ein paar Steaks erzeugt.',
            ),
            'grill2' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Zombieleiche grillen',
                'energy' => 10,
                'requires' => Array('Model_Items_Body2' => 1),
                'produces' => Array('Model_Items_Steak' => 2),
                'achievement' => null,
                'finalmsg'	=> 'Mit einem Grill kannst du selbst das ekelhafteste Zeug schmackhaft machen. Herzlichen Glückwunsch, du hast ein paar Steaks erzeugt.',
            ),
            'grill3' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Tierkadaver grillen',
                'energy' => 5,
                'requires' => Array('Model_Items_Body3' => 1),
                'produces' => Array('Model_Items_Steak' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit einem Grill kannst du selbst das ekelhafteste Zeug schmackhaft machen. Herzlichen Glückwunsch, du hast ein paar Steaks erzeugt.',
            )
        ),
        'Model_Places_Xmasfair' => array(
            'lametta' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Lametta herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Cd' => 3),
                'produces' => Array('Model_Items_Generic_Lametta' => 1),
                'finalmsg'	=> 'Nichts macht mehr Spaß als an Weihnachten etwas schönes zu basteln. Du hast soeben Dekoration hergestellt.',
                'achievement' => null,
            ),
            'rope' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Schmuckseil herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Lametta' => 2, 'Model_Items_Generic_Wire' => 1),
                'produces' => Array('Model_Items_Generic_Xmasrope' => 1),
                'finalmsg'	=> 'Nichts macht mehr Spaß als an Weihnachten etwas schönes zu basteln. Du hast soeben Dekoration hergestellt.',
                'achievement' => null,
            ),
            'leds' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'LED-Lichterkette herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Electro' => 1, 'Model_Items_Generic_Wire' => 1, 'Model_Items_Generic_Led' => 10),
                'produces' => Array('Model_Items_Generic_Xmaslights' => 1),
                'finalmsg'	=> 'Nichts macht mehr Spaß als an Weihnachten etwas schönes zu basteln. Du hast soeben Dekoration hergestellt.',
                'achievement' => null,
            ),
            'mistletoe' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Mistelzweig herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Bauble' => 3, 'Model_Items_Stick' => 2, 'Model_Items_Generic_Ducttape' => 1, 'Model_Items_Generic_Xmasneedles' => 1),
                'produces' => Array('Model_Items_Generic_Mistletoe' => 1),
                'finalmsg'	=> 'Nichts macht mehr Spaß als an Weihnachten etwas schönes zu basteln. Du hast soeben Dekoration hergestellt.',
                'achievement' => null,
            ),
        ),
	),
);