<?php defined('SYSPATH') or die('No direct access allowed.');

return array(
	'kitchen' => array(
		'table' => array(

			'xmas1' => Array(
					'obvious' => false,
					'keys' => Array("Model_Items_Generic_Cookieproto"),
					'base' => 'kitchen',
					'environment' => Array("base", "utils"),
					'text' => 'Plätzchen backen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Cookieproto' => 1),
					'produces' => Array('Model_Items_Cookie' => 5),
					'achievement' => null,
					'finalmsg'	=> 'Ein weihnachtlicher Durft erfüllt dein Versteck, als du kleine Figürchen aus dem Teig presst und diese zu Plätzchen backst.',
			),
			'xmas2' => Array(
					'obvious' => false,
					'keys' => Array("Model_Items_Generic_Cookieproto"),
					'base' => 'kitchen',
					'environment' => Array("base", "utils"),
					'text' => 'Besondere Plätzchen backen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Cookieproto' => 1, 'Model_Items_Powderpack' => 1),
					'produces' => Array('Model_Items_Cookie2' => 5),
					'achievement' => null,
					'finalmsg'	=> 'Normale Plätzchen sind langweilig, also fügst du ein paar kreative Extra-Zutaten hinzu...',
			),
		)	
	),
		
	'workshop' => array(

        'table' => array(

			'srv_sum' => Array(
                'condition' => function($l) {global $player; return $player->job(1060);},
                'obvious' => true,
                'cat' => 'create',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Selbstgebaute Kleinteile herstellen',
                'energy' => 25,
                'requires' => Array('Model_Items_Generic_Crmetal' => 5),
                'produces' => Array('Model_Items_Generic_Sum' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Großartig - andere hätten diese Kleinteile mühsam zusammensuchen müssen, du kannst sie einfach selbst herstellen!',
			),
			'srv_mat' => Array(
                'condition' => function($l) {global $player; return $player->job(1060);},
                'obvious' => true,
                'cat' => 'create',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Flickenmatratze herstellen',
                'energy' => 25,
                'requires' => Array('Model_Items_Generic_Cloth' => 8),
                'produces' => Array('Model_Items_Generic_Bed' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Keine Ahnung wozu du als Survivalist überhaupt eine Matratze brauchst... aber gut, wenn du Spaß an Bastelarbeit hast.',
			),
			'srv_tbl' => Array(
                'condition' => function($l) {global $player; return $player->job(1060);},
                'obvious' => true,
                'cat' => 'create',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Provisorischen Tisch herstellen',
                'energy' => 25,
                'requires' => Array('Model_Items_Generic_Wood' => 7),
                'produces' => Array('Model_Items_Generic_Table' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Wer braucht schon EKEA? Dieser Tisch hat eine mindestens genauso fragwürdige Qualität, und er ist aus echtem undefinierbaren Holz!.',
			),
			'tech' => Array(
                'condition' => function($l) {global $player; return $player->job(3030);},
                'obvious' => true,
                'cat' => 'assemble',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Lasermessgerät herstellen',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 1, 'Model_Items_Generic_Tube' => 1),
                'produces' => Array('Model_Items_Generic_Lasermapper' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Wer braucht schon EKEA? Dieser Tisch hat eine mindestens genauso fragwürdige Qualität, und er ist aus echtem undefinierbaren Holz!.',
			),
			'crwood' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Holzbrett herstellen',
                'energy' => 6,
                'requires' => Array('Model_Items_Generic_Crwood' => 4),
                'produces' => Array('Model_Items_Generic_Wood' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Gäbe es einen Gott für Recycling, er wäre sicherlich stolz auf dich!',
			),
			'crmetal' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Altmetall herstellen',
                'energy' => 6,
                'requires' => Array('Model_Items_Generic_Crmetal' => 4),
                'produces' => Array('Model_Items_Generic_Metal' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Gäbe es einen Gott für Recycling, er wäre sicherlich stolz auf dich!',
			),
			'crwood2' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'create',
                'environment' => Array("elec"),
                'text' => 'Holzbrett effizient herstellen',
                'energy' => 0,
                'requires' => Array('Model_Items_Generic_Crwood' => 4, 'Model_Items_Energy' => 2),
                'produces' => Array('Model_Items_Generic_Wood' => 3),
                'achievement' => null,
                'finalmsg'	=> 'Gäbe es einen Gott für Recycling, er wäre sicherlich enorm stolz auf dich!',
			),
			'crmetal2' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("elec"),
                'text' => 'Altmetall effizient herstellen',
                'energy' => 0,
                'requires' => Array('Model_Items_Generic_Crmetal' => 4, 'Model_Items_Energy' => 2),
                'produces' => Array('Model_Items_Generic_Metal' => 3),
                'achievement' => null,
                'finalmsg'	=> 'Gäbe es einen Gott für Recycling, er wäre sicherlich enorm stolz auf dich!',
			),
            'bolts1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Bolzen fertigen',
                'energy' => 2,
                'requires' => Array('Model_Items_Generic_Crwood' => 1),
                'produces' => Array('Model_Items_Bolts' => 3),
                'achievement' => null,
                'finalmsg'	=> 'Wäre dies ein Vampirspiel, so wärst du mit diesen Bolzen perfekt ausgerüstet, um Dracula gegenüber zu treten. Leider ist dies ein Zombiespiel, also wirst du wohl doch zur Armbrust greifen müssen...',
            ),
            'bolts2' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Bolzen fertigen',
                'energy' => 3,
                'requires' => Array('Model_Items_Generic_Wood' => 1),
                'produces' => Array('Model_Items_Bolts' => 10),
                'achievement' => null,
                'finalmsg'	=> 'Wäre dies ein Vampirspiel, so wärst du mit diesen Bolzen perfekt ausgerüstet, um Dracula gegenüber zu treten. Leider ist dies ein Zombiespiel, also wirst du wohl doch zur Armbrust greifen müssen...',
            ),
			'bbag1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'create',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Leichensack herstellen',
                'energy' => 15,
                'requires' => Array('Model_Items_Generic_Cloth' => 8),
                'produces' => Array('Model_Items_Bodybag' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Ein Stich hier.... ein Stich dort... Fertig! Dieser stylische Leichensack wird deine Transportprobleme zumindest im Bezug auf Leichen für immer lösen!',
			),
			'bbag2' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Bodybag4'),
                'cat' => 'fix',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Leichensack provisorisch flicken',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Cloth' => 3, 'Model_Items_Bodybag4' => 1),
                'produces' => Array('Model_Items_Bodybag2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Du fühlst sich wie eine Art makabrer Modedesigner! Ein paar Sticke mit der Nadel, schon ist dieser hässliche Riss fast nicht mehr zu sehen.',
			),
			'bbag3' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Bodybag4'),
                'base' => 'manu',
                'cat' => 'fix',
                'environment' => Array("base"),
                'text' => 'Leichensack gründlich flicken',
                'energy' => 9,
                'requires' => Array('Model_Items_Generic_Cloth' => 5, 'Model_Items_Bodybag4' => 1),
                'produces' => Array('Model_Items_Bodybag' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Du fühlst sich wie eine Art makabrer Modedesigner! Ein paar Sticke mit der Nadel, schon ist dieser hässliche Riss nicht mehr zu sehen. Und ein paar potentielle Schwachstellen hast du gleich mit ausgebessert! Bravo!',
			),
			'skel' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Generic_Bone3'),
                'cat' => 'disassemble',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Knochen sortieren',
                'short'     => 'Sortierte Knochen',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Bone3' => 1),
                'produces' => Array('Model_Items_Bone' => 8, 'Model_Items_Bone2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Endlich kannst du deine destruktiven Energien mal an was anderem als an Zombies ausleben. Aus irgend einem Grund bereitet dir das Auseinandernehmen dieses Skeletts eine merkwürdige Befriedigung...',
			),
            'bat1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Schläger aufpeppen',
                'energy' => 20,
                'requires' => Array('Model_Items_Bat' => 1, 'Model_Items_Generic_Ducttape' => 2, 'Model_Items_Generic_Crmetal' => 4),
                'produces' => Array('Model_Items_Bat2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit diesem Schläger fährst du keine Homerun-Rekorde mehr ein... Dafür ist er wesentlich Effektiver im Bereich "Zombieverstümmelung".',
            ),
            'crossbow' => Array(
                'obvious' => true,
                'cat' => 'assemble',
                'keys' => null,
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Armbrust herstellen',
                'energy' => 50,
                'requires' => Array('Model_Items_Generic_Wire' => 1, 'Model_Items_Generic_Wood' => 2, 'Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 1),
                'produces' => Array('Model_Items_Crossbow' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Du hast eine Armbrust hergestellt. Wie wärs, wenn du direkt mal mit Zielübungen auf ein paar Zombies beginnst?',
            ),
			'batgun1' => Array(
                'obvious' => true,
                'keys' => Array('Model_Items_Batgun'),
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Ladevorrichtung des Batteriewerfers verbessern',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Ducttape' => 1, 'Model_Items_Generic_Tube' => 1, 'Model_Items_Batgun' => 1),
                'produces' => Array('Model_Items_Batgun2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit ein paar kleinen Verbesserungen kann man die Effektivität eines Batteriewerfers ungemein erhöhen. Mit der neuen Ladevorrichtung sparst du im Kampf viel Zeit, die du wiederum in das Abschlachten weiterer Zombies investieren kannst.',
			),
			'batgun2' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Batgun2'),
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("elec"),
                'text' => 'Batteriewerfer zum Mark II umbauen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Pressure' => 1, 'Model_Items_Generic_Sum' => 2, 'Model_Items_Generic_Tube' => 1, 'Model_Items_Batgun2' => 1),
                'produces' => Array('Model_Items_Batgun3' => 1),
                'achievement' => Model_Achievement::MA_BUILD_MKII,
                'finalmsg'	=> 'Mit ein paar kleinen Verbesserungen kann man die Effektivität eines Batteriewerfers ungemein erhöhen. Der neue Druckregler passt die Abschussgeschwindigkeit genau der Entfernung an und erhöht so deine Treffsicherheit. Mit ein wenig Glück kannst du mit einer Baterie sogar zwei Zombies erwischen!',
			),
            'aquagun1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("elec"),
                'text' => 'Wasserpistole verbessern',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Pressure' => 1, 'Model_Items_Generic_Sum' => 1, 'Model_Items_Generic_Tube' => 4, 'Model_Items_Watergun' => 1),
                'produces' => Array('Model_Items_Watergun2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Es ist wirklich überhaupt nicht bizarr, wenn erwachsene Überlebende einer Apokalypse durch die Ruinen der Zivilisation rennen und mit militärischen Wasserpistolen um sich spritzen! Hört auch zu lachen!',
            ),
            'splintergun1' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("elec"),
                'text' => 'Splitterwerfer zum Mark II umbauen',
                'energy' => 25,
                'requires' => Array('Model_Items_Generic_Pressure' => 1, 'Model_Items_Generic_Sum' => 2, 'Model_Items_Generic_Tube' => 1, 'Model_Items_Generic_Metal' => 3, 'Model_Items_Splintergun' => 1),
                'produces' => Array('Model_Items_Splintergun2' => 1),
                'achievement' => Model_Achievement::MA_BUILD_MKII,
                'finalmsg'	=> 'Was kann man mit einer verrückten Waffe machen? Sie NOCH verrückter machen, natürlich! Was denn sonst?',
            ),
            'clothes_impr' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Kleidung verbessern',
                'energy' => 15,
                'requires' => Array('Model_Items_Clothes' => 1, 'Model_Items_Generic_Cloth' => 1, 'Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Crmetal' => 4),
                'produces' => Array('Model_Items_Clothes2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Normalerweise würde kein Mensch so etwas machen - aber in der aktuellen Situation ist es tatsächlich notwendig, seine Bequemlichkeit zugunsten von etwas mehr Sicherheit zu opfern.',
            ),
            'clothes_fix' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'fix',
                'environment' => Array("base"),
                'text' => 'Kleidung nähen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Clothes' => 1, 'Model_Items_Generic_Cloth' => 2),
                'produces' => Array('Model_Items_Clothes' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Es sieht etwas zusammengeschustert aus... aber wenigstens musst du nun nicht mehr in Unterwäsche herumlaufen.',
            ),
            'shield' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'assemble',
                'environment' => Array("base"),
                'text' => 'Einfachen Holzkistendeckel bauen',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Wood' => 4, 'Model_Items_Generic_Ducttape' => 1),
                'produces' => Array('Model_Items_Shield' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Hierfür muss man wahrlich kein Meister der Handwerkskunst sein. Du hast einen Holzkistendeckel zusammengebaut.',
            ),
            'shield2' => Array(
                'obvious' => true,
                'keys' => null,
                'cat' => 'upgrade',
                'base' => 'manu',
                'environment' => Array("base"),
                'text' => 'Holzkistendeckel stabilisieren',
                'energy' => 20,
                'requires' => Array('Model_Items_Shield' => 1, 'Model_Items_Generic_Wood' => 4, 'Model_Items_Generic_Sum' => 1),
                'produces' => Array('Model_Items_Shield2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit ein bisschen mehr Holz (und Schrauben anstelle von Klebeband) hast du deinen Holzkistendeckel stabilisiert.',
            ),
            'helmet' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'upgrade',
                'environment' => Array("base"),
                'text' => 'Fahrradhelm verbessern',
                'energy' => 20,
                'requires' => Array('Model_Items_Helmet' => 1, 'Model_Items_Generic_Metal' => 4, 'Model_Items_Generic_Sum' => 1),
                'produces' => Array('Model_Items_Helmet2' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit ein bisschen Metall (und Schrauben anstelle von Klebeband) hast du deinen Fahrradhelm verbessert.',
            ),
			'ripbed' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("base"),
                'text' => 'Matratze auseinanderschneiden',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Bed' => 1),
                'produces' => Array('Model_Items_Generic_Cloth' => 5),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'ripboil' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("base"),
                'text' => 'Wasserkocher auseinandernehmen',
                'short'     => 'Wasserkocher-Bauteile',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Boiler' => 1),
                'produces' => Array('Model_Items_Generic_Crmetal' => 1, 'Model_Items_Generic_Electro' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'ripmix' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("base"),
                'text' => 'Handmixer auseinandernehmen',
                'short'     => 'Handmixer-Bauteile',
                'energy' => 6,
                'requires' => Array('Model_Items_Generic_Mixer' => 1),
                'produces' => Array('Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 2),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'riptable' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("base"),
                'text' => 'Järpentisch auseinandernehmen',
                'short'     => 'Järpen-Bauteile',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Table' => 1),
                'produces' => Array('Model_Items_Generic_Wood' => 5, 'Model_Items_Generic_Sum' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'rippressure' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("elec"),
                'text' => 'Druckregler auseinandernehmen',
                'short'     => 'Druckregler-Bauteile',
                'energy' => 30,
                'requires' => Array('Model_Items_Generic_Pressure' => 1),
                'produces' => Array('Model_Items_Generic_Metal' => 1, 'Model_Items_Generic_Sum' => 3, 'Model_Items_Generic_Tube' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'ripmotor' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("elec"),
                'text' => 'Motor auseinandernehmen',
                'short'     => 'Motor-Bauteile',
                'energy' => 50,
                'requires' => Array('Model_Items_Generic_Motor' => 1),
                'produces' => Array('Model_Items_Generic_Metal' => 7, 'Model_Items_Generic_Electro' => 3, 'Model_Items_Generic_Tube' => 5),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'ripoven' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'disassemble',
                'environment' => Array("elec"),
                'text' => 'Ofen auseinandernehmen',
                'short'     => 'Ofen-Bauteile',
                'energy' => 50,
                'requires' => Array('Model_Items_Generic_Oven' => 1),
                'produces' => Array('Model_Items_Generic_Metal' => 5, 'Model_Items_Generic_Sum' => 5, 'Model_Items_Generic_Cloth' => 2),
                'achievement' => null,
                'finalmsg'	=> 'Dieses Teil hast du eh nicht mehr gebraucht... und warum soll es rumliegen und Platz verschwenden, wenn du es einfach auseinandernehmen kannst?',
			),
			'pbomb' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'assemble',
                'environment' => Array("base"),
                'text' => 'Schwarzpulverbombe bauen',
                'energy' => 1,
                'requires' => Array('Model_Items_Generic_Ducttape' => 1, 'Model_Items_Generic_Gunpowder' => 1, 'Model_Items_Generic_Plasticbag' => 1),
                'produces' => Array('Model_Items_Powderbomb' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Vorsichtig füllst du das Schwarzpulver in eine Plastiktüte... BINGO! Perfekte Schwarzpulverbombe! Dieses Teil wird dir sicher irgendwann einmal das Leben retten.',
			),
			'halloween' => Array(
                'obvious' => false,
                'keys' => Array('Model_Items_Generic_Pumpkin'),
                'base' => 'manu',
                'cat' => 'assemble',
                'environment' => Array("base"),
                'text' => 'Kürbisbombe bauen',
                'energy' => 10,
                'requires' => Array('Model_Items_Generic_Pumpkin' => 1, 'Model_Items_Generic_Gunpowder' => 5),
                'produces' => Array('Model_Items_Pumpkinbomb' => 1),
                'achievement' => Model_Achievement::MA_PUMPKINHEAD,
                'finalmsg'	=> 'So ein Kürbis kann sicher toll explodieren, wenn man ihn bis zum Rand mit Schwarzpulver vollstopft! Und das Gesicht.... naja, der Kürbis hätt halt ohne einfach doof ausgesehen.',
			),
            'bandage' => Array(
                'obvious' => true,
                'keys' => null,
                'base' => 'manu',
                'cat' => 'assemble',
                'environment' => Array("base"),
                'text' => 'Provisorische Bandage herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Cloth' => 2, 'Model_Items_Whiskey' => 1),
                'produces' => Array('Model_Items_Bandage2' => 1, 'Model_Items_Smallbottle' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Also, so richtig hygienisch sieht das jetzt nicht aus...',
            )
		)
	),
	
	'lda' => array(
		'Model_Places_Burgerjoint' => array(
			'body' => Array(
					'obvious' => true,
					'keys' => null,
					'text' => 'Leiche frittieren',
					'energy' => 15,
					'requires' => Array('Model_Items_Body' => 1, 'Model_Items_Generic_Supercharger' => 2),
					'produces' => Array('Model_Items_Bodycrisp' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Alles wird leckerer, wenn man es frittiert - das wusste schon Homer Simpson. Jetzt gilt es herauszufinden, ob das auch mit Leichen funktioniert...',
			),
			'coffee' => Array(
					'obvious' => true,
					'keys' => null,
					'text' => 'Kaffee kochen',
					'energy' => 0,
					'requires' => Array('Model_Items_Coffee' => 1, 'Model_Items_Generic_Supercharger' => 1),
					'produces' => Array('Model_Items_Coffee2' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Erschöpft vom Zombieapokalypse-Alltag setzt du dir erstmal eine schöne Kanne Kaffee auf.',
			),
			'water' => Array(
					'obvious' => true,
					'keys' => null,
					'text' => 'Wasser abkochen',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Waterv' => 1, 'Model_Items_Generic_Supercharger' => 1),
					'produces' => Array('Model_Items_Generic_Water0' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Das Wasser in deiner Flasche schaut dich mit großen, traurigen Augen an - aber das hilft nicht viel. Eiskalt kochst du es auf 100° und tötest so alles Leben darin ab!',
			),
		),
		'Model_Places_Weaponshop' => array(
			'machete' => Array(
					'obvious' => false,
					'keys' => Array('Model_Items_Machete'),
					'text' => 'Machete schleifen',
					'energy' => 25,
					'requires' => Array('Model_Items_Machete' => 1),
					'produces' => Array('Model_Items_Machete2' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Deine Machete sieht schon ziemlich stumpf und rostig aus, also bringst du sie mit diesem praktischen Schleifstein wieder auf Vordermann.',
			),
			'bnmachete' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Machete verbessern',
					'energy' => 15,
					'requires' => Array('Model_Items_Machete2' => 1, 'Model_Items_Bandage' => 1, 'Model_Items_Generic_Ducttape' => 2),
					'produces' => Array('Model_Items_Macheteband' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Du nimmst die Bandage, wickelst die um den Griff der Machete und befestigst die Enden mit ein wenig Klebeband. Toll, nun kannst du deine Machete viel einfacher halten und es besteht keine Gefahr mehr, beim Metzeln (oder bei der Intimrasur) abzurutschen.',
			),
			'dlmachete' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Coole Machetenposen üben',
					'energy' => 5,
					'requires' => Array('Model_Items_Machete2' => 2),
					'produces' => Array('Model_Items_Macheteduo' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Wenn du schon ganz allein gegen Zombies kämpfen musst, kannst du dabei wenigstens cool aussehen. Leider ist niemand mehr da, um ein Video von deiner coolen neuen Choreographie bei YouTube zu posten.',
			),
			'plasma' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Plasmakanone bauen',
					'energy' => 60,
					'requires' => Array('Model_Items_Generic_Plasma' => 1, 'Model_Items_Generic_Electro' => 1, 'Model_Items_Handgun' => 1, 'Model_Items_Batgun' => 1),
					'produces' => Array('Model_Items_Plasmagun' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Gut, dass dieser hochgradig experimentelle Plasmablitz-Generator eine absolut standartkonforme Bauform sowie Anschlüsse besitzt, sodass du ihn mit Bauteilen deines Batteriewerfers und Revolvers in eine tödliche Waffe verwandeln kannst. Fast könnte man meinen, das ganze wäre ziemlich unrealistisch.... aber nur fast!',
			),
			'splbatgun' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Batteriewerfer pimpen',
					'energy' => 5,
					'requires' => Array('Model_Items_Generic_Pressure' => 3, 'Model_Items_Generic_Sum' => 1, 'Model_Items_Batgun2' => 1),
					'produces' => Array('Model_Items_Batgunsplat' => 1),
					'finalmsg'	=> 'Viel hilft viel - mit ein paar zusätzlichen Druckreglern kannst du Batterien nun mit extra-hoher Geschwindigkeit abfeuern.',
			),
			'snpbatgun' => Array(
					'condition' => function($l) {global $game; return $game->config('modules.armory');},
					'obvious' => true,
					'text' => 'Scharfschützen-Batteriewerfer bauen',
					'energy' => 5,
					'requires' => Array('Model_Items_Generic_Tube' => 5, 'Model_Items_Generic_Sum' => 2, 'Model_Items_Batgun2' => 1),
					'produces' => Array('Model_Items_Batgunsnp' => 1),
					'finalmsg'	=> 'Verlängerter Lauf: Check. Feinjustierte Abschussvorrichtung: Check. Rosa glitzernder Ponyaufkleber: Check. Tötungsmaschine: Bereit!',
			),
			'ammo' => Array(
					'obvious' => true,
					'keys' => null,
					'text' => 'Munition produzieren',
					'energy' => 0,
					'requires' => Array('Model_Items_Generic_Tube' => 1, 'Model_Items_Generic_Gunpowder' => 1),
					'produces' => Array('Model_Items_Ammo' => 1),
					'achievement' => null,
					'finalmsg'	=> 'Anscheinend kann man sich Munition ganz einfach selber bauen, indem man ein Kupferrohr in kleine Stücke sägt und mit Schwarzpulver füllt. Wer hätte das gedacht?',
			),
		),
        'Model_Places_Camping_Grill' => array(
            'grill1' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Leiche grillen',
                'energy' => 10,
                'requires' => Array('Model_Items_Body' => 1),
                'produces' => Array('Model_Items_Steak' => 3),
                'achievement' => null,
                'finalmsg'	=> 'Mit einem Grill kannst du selbst das ekelhafteste Zeug schmackhaft machen. Herzlichen Glückwunsch, du hast ein paar Steaks erzeugt.',
            ),
            'grill2' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Zombieleiche grillen',
                'energy' => 10,
                'requires' => Array('Model_Items_Body2' => 1),
                'produces' => Array('Model_Items_Steak' => 2),
                'achievement' => null,
                'finalmsg'	=> 'Mit einem Grill kannst du selbst das ekelhafteste Zeug schmackhaft machen. Herzlichen Glückwunsch, du hast ein paar Steaks erzeugt.',
            ),
            'grill3' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Tierkadaver grillen',
                'energy' => 5,
                'requires' => Array('Model_Items_Body3' => 1),
                'produces' => Array('Model_Items_Steak' => 1),
                'achievement' => null,
                'finalmsg'	=> 'Mit einem Grill kannst du selbst das ekelhafteste Zeug schmackhaft machen. Herzlichen Glückwunsch, du hast ein paar Steaks erzeugt.',
            )
        ),
        'Model_Places_Xmasfair' => array(
            'lametta' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Lametta herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Cd' => 3),
                'produces' => Array('Model_Items_Generic_Lametta' => 1),
                'finalmsg'	=> 'Nichts macht mehr Spaß als an Weihnachten etwas schönes zu basteln. Du hast soeben Dekoration hergestellt.',
                'achievement' => null,
            ),
            'rope' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Schmuckseil herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Lametta' => 2, 'Model_Items_Generic_Wire' => 1),
                'produces' => Array('Model_Items_Generic_Xmasrope' => 1),
                'finalmsg'	=> 'Nichts macht mehr Spaß als an Weihnachten etwas schönes zu basteln. Du hast soeben Dekoration hergestellt.',
                'achievement' => null,
            ),
            'leds' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'LED-Lichterkette herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Electro' => 1, 'Model_Items_Generic_Wire' => 1, 'Model_Items_Generic_Led' => 10),
                'produces' => Array('Model_Items_Generic_Xmaslights' => 1),
                'finalmsg'	=> 'Nichts macht mehr Spaß als an Weihnachten etwas schönes zu basteln. Du hast soeben Dekoration hergestellt.',
                'achievement' => null,
            ),
            'mistletoe' => Array(
                'obvious' => true,
                'keys' => Array(),
                'text' => 'Mistelzweig herstellen',
                'energy' => 5,
                'requires' => Array('Model_Items_Generic_Bauble' => 3, 'Model_Items_Stick' => 2, 'Model_Items_Generic_Ducttape' => 1, 'Model_Items_Generic_Xmasneedles' => 1),
                'produces' => Array('Model_Items_Generic_Mistletoe' => 1),
                'finalmsg'	=> 'Nichts macht mehr Spaß als an Weihnachten etwas schönes zu basteln. Du hast soeben Dekoration hergestellt.',
                'achievement' => null,
            ),
        ),
	),
);