<?php defined('SYSPATH') or die('No direct access allowed.');

    return Model_Factory_Items::factory()
        ->add('Model_Items_Generic_Wire'        , 1)
        ->add('Model_Items_Generic_Jerrycan'	, 1)
        ->add('Model_Items_Generic_Sum'		    , 2)
        ->add('Model_Items_Generic_Metal'		, 4)
        ->add('Model_Items_Generic_Tube'		, 3)
        ->add('Model_Items_Generic_Wood'		, 3)
        ->add('Model_Items_Generic_Ducttape'	, 4)
        ->add('Model_Items_Generic_Motor'		, 1)
        ->add('Model_Items_Battery'			    , 3)
        ->add('Model_Items_Generic_Gunpowder'	, 1)
        ->add('Model_Items_Generic_Bed'		    , 1)
        ->add('Model_Items_Generic_Electro'	    , 2)
        ->add('Model_Items_Generic_Pressure'	, 2)
        ->add('Model_Items_Generic_Plasticbag'  , 2)
        ->add('Model_Items_Money'				, 2)
        ->add('Model_Items_Generic_Table'		, 2)
        ->add('Model_Items_Chainsaw'            , 1)
        ->add('Model_Items_Booklet'             , 2)
        ->add('Model_Items_Shield'	            , 2)
        ->add('Model_Items_Helmet'              , 2)
        ->add('Model_Items_Bat'                 , 1)
        ->add('Model_Items_Shield3'             , 1)
        ->add('Model_Items_Phone'               , 1)
        ->add('Model_Items_Flashlight'          , 1)
        ->add('Model_Items_Generic_Bike'        , 1)
        ->add('Model_Items_Tentkit'             , 1)
        ->add('Model_Items_Generic_Belt'        , 1)
        ->add('Model_Items_Concrete'            , 1)

        ->add(Model_Items_Virtual_Invoke_Animal::cls()        , 1)
        ;