<?php defined('SYSPATH') or die('No direct access allowed.');

    return Model_Factory_Items::factory()
        ->add(Model_Items_Generic_Wire::cls()       , 1)
        ->add(Model_Items_Generic_Jerrycan::cls()	, 1)
        ->add(Model_Items_Generic_Sum::cls()		    , 2)
        ->add(Model_Items_Generic_Metal::cls()		    , 4)
        ->add(Model_Items_Generic_Tube::cls()		    , 3)
        ->add(Model_Items_Generic_Wood::cls()		    , 3)
        ->add(Model_Items_Generic_Ducttape::cls()	, 4)
        ->add(Model_Items_Generic_Motor::cls()		    , 1)
        ->add(Model_Items_Battery::cls()			    , 3)
        ->add(Model_Items_Generic_Gunpowder::cls()	, 1)
        ->add(Model_Items_Generic_Bed::cls()		    , 1)
        ->add(Model_Items_Generic_Electro::cls()	    , 2)
        ->add(Model_Items_Generic_Pressure::cls()	, 2)
        ->add(Model_Items_Generic_Plasticbag::cls() , 2)
        ->add(Model_Items_Money::cls()			    , 2)
        ->add(Model_Items_Generic_Table::cls()	    , 2)
        ->add(Model_Items_Chainsaw::cls()           , 1)
        ->add(Model_Items_Booklet::cls()            , 2)
        ->add(Model_Items_Shield::cls()	            , 2)
        ->add(Model_Items_Helmet::cls()             , 2)
        ->add(Model_Items_Bat::cls()                , 1)
        ->add(Model_Items_Shield3::cls()            , 1)
        ->add(Model_Items_Phone::cls()              , 1)
        ->add(Model_Items_Flashlight::cls()         , 1)
        ->add(Model_Items_Generic_Bike::cls()       , 1)
        ->add(Model_Items_Tentkit::cls()            , 1)
        ->add(Model_Items_Generic_Belt::cls()       , 1)
        ->add(Model_Items_Concrete::cls()           , 1)
        ->add(Model_Items_Generic_Spraycan::cls(), 1)

        ->add(Model_Items_Virtual_Invoke_Animal::cls()        , 1)
        ;