<?php defined('SYSPATH') or die('No direct access allowed.');

    return Model_Factory_Items::factory()
        ->add(Model_Items_Chem::cls()			, 2)
        ->add(Model_Items_Powderpack::cls()		, 1)
        ->add(Model_Items_Nutrient::cls()		, 1)
        ->add(Model_Items_Pill::cls()			, 2)
        ->add(Model_Items_Bandage::cls()			, 1)
        ->add('gp_alcohol'						, 1)
        ->add(Model_Items_Generic_Micropur::cls(), 1)
        ->add(Model_Items_Generic_Oven::cls()	, 1)
        ->add(Model_Items_Money::cls()			, 2)
        ->add(Model_Items_Generic_Table::cls()	, 1)
        ->add(Model_Items_Meds::cls()            , 1)
        ->add(Model_Items_Dildo::cls()           , 1)
        ->add(Model_Items_Generic_Spice::cls()   , 1)
        ->add(Model_Items_Shield::cls()	        , 1)
        ->add(Model_Items_Helmet::cls()          , 2)
        ->add(Model_Items_Jacket::cls()          , 1)
        ->add(Model_Items_Shield3::cls()         , 1)
        ->add(Model_Items_Morphine::cls()        , 1)
        ->add(Model_Items_Bigbottle::cls(), 1)

        ->add(Model_Items_Virtual_Invoke_Animal::cls()        , 1)
        ;