<?php defined('SYSPATH') or die('No direct access allowed.');

    return Model_Factory_Items::factory()
        ->add(Model_Items_Generic_Bed::cls()		    , 1)
        ->add('gp_body'          			    , 5)
        ->add(Model_Items_Battery::cls()			    , 3)
        ->add(Model_Items_Generic_Lamp::cls()	    , 1)
        ->add(Model_Items_Ammo::cls()			    , 1)
        ->add(Model_Items_Handgun::cls()			    , 1)
        ->add(Model_Items_Oldrifle::cls()            , 1)
        ->add(Model_Items_Generic_Gunpowder::cls()	, 2)
        ->add(Model_Items_Generic_Cloth::cls()		, 3)
        ->add('gp_water'						, 2)
        ->add(Model_Items_Generic_Plasticbag::cls()  , 1)
        ->add(Model_Items_Generic_Teddy::cls()		, 2)
        ->add(Model_Items_Bottle::cls()			    , 1)
        ->add(Model_Items_Knife::cls()				, 2)
        ->add(Model_Items_Generic_Oven::cls()		, 1)
        ->add(Model_Items_Money::cls()				, 1)
        ->add(Model_Items_Generic_Table::cls()		, 1)
        ->add(Model_Items_Chainsaw::cls()            , 1)
        ->add(Model_Items_Bandage2::cls()            , 2)
        ->add(Model_Items_Meds::cls()                , 1)
        ->add(Model_Items_Dalad::cls()               , 1)
        ->add(Model_Items_Dildo::cls()               , 1)
        ->add('gp_literature'                   , 1)
        ->add(Model_Items_Shield::cls()	            , 1)
        ->add(Model_Items_Vest::cls()                , 1)
        ->add(Model_Items_Bat::cls()                 , 2)
        ->add(Model_Items_Jacket::cls()              , 1)
        ->add(Model_Items_Phone::cls()               , 1)
        ->add(Model_Items_Flashlight::cls()          , 2)
        ->add(Model_Items_Tentkit::cls()             , 1)
        ->add(Model_Items_Generic_Belt::cls()        , 1)
        ->add('gp_petstuff', 1)

        ->add(Model_Items_Virtual_Invoke_Animal::cls()        , 1)
        ;