<?php defined('SYSPATH') or die('No direct access allowed.');

    return Model_Itemfactory::factory()
        ->add('Model_Items_Generic_Bed'		    , 1)
        ->add('gp_body'          			    , 5)
        ->add('Model_Items_Battery'			    , 3)
        ->add('Model_Items_Generic_Lamp'	    , 1)
        ->add('Model_Items_Ammo'			    , 1)
        ->add('Model_Items_Handgun'			    , 1)
        ->add('Model_Items_Oldrifle'            , 1)
        ->add('Model_Items_Generic_Gunpowder'	, 2)
        ->add('Model_Items_Generic_Cloth'		, 3)
        ->add('gp_water'						, 2)
        ->add('Model_Items_Generic_Plasticbag'  , 1)
        ->add('Model_Items_Generic_Teddy'		, 2)
        ->add('Model_Items_Bottle'			    , 1)
        ->add('Model_Items_Knife'				, 2)
        ->add('Model_Items_Generic_Oven'		, 1)
        ->add('Model_Items_Money'				, 1)
        ->add('Model_Items_Generic_Table'		, 1)
        ->add('Model_Items_Chainsaw'            , 1)
        ->add('Model_Items_Bandage2'            , 2)
        ->add('Model_Items_Meds'                , 1)
        ->add('Model_Items_Dalad'               , 1)
        ->add('Model_Items_Dildo'               , 1)
        ->add('gp_literature'                   , 1)
        ->add('Model_Items_Shield'	            , 1)
        ->add('Model_Items_Vest'                , 1)
        ->add('Model_Items_Bat'                 , 2)
        ->add('Model_Items_Jacket'              , 1)
        ->add('Model_Items_Phone'               , 1)
        ->add('Model_Items_Flashlight'          , 2)
        ->add('Model_Items_Tentkit'             , 1)
        ->add('Model_Items_Generic_Belt'        , 1)
        ;